### ISSUE TITLE
undefined class/module AdditionalImageImageUploader::Uploader70144767401600

### ISSUE THREAD

**Issue by dblock** [carrierwaveuploader/carrierwave#1001]
When restarting Rails (or redeploing an app), any cached reference to an object with an uploader will fail to deserialize with this:

```
ArgumentError: undefined class/module AdditionalImageImageUploader::Uploader70144767401600
/Users/dblock/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.12/lib/active_support/cache.rb:587:in `load'
/Users/dblock/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.12/lib/active_support/cache.rb:587:in `value'
/Users/dblock/.rvm/gems/ruby-1.9.3-p385/gems/activesupport-3.2.12/lib/active_support/cache.rb:294:in `fetch'
/Users/dblock/source/gravity/dblock/app/controllers/artworks_controller.rb:11:in `show'
/Users/dblock/.rvm/gems/ruby-1.9.3-p385/gems/actionpack-3.2.12/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/Users/dblock/.rvm/gems/ruby-1.9.3-p385/gems/actionpack-3.2.12/lib/abstract_controller/base.rb:167:in `process_action'
/Users/dblock/.rvm/gems/ruby-1.9.3-p385/gems/actionpack-3.2.12/lib/action_controller/metal/rendering.rb:10:in `process_action'
/Users/dblock/.rvm/gems/ruby-1.9.3-p385/gems/actionpack-3.2.12/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
```

There's a dynamic class being created in the uploader models, which doesn't exist when it gets de-serialized from cache after the server is restarted. This makes objects that have an uploader un-cacheable.

**Comment by nocturnaltortoise** [comment]
I have the same issue when using Carrierwave with paper_trail (https://github.com/airblade/paper_trail), does anyone know of a fix for this?
