### ISSUE TITLE
Errno::ENOENT: No such file or directory - /tmp/mini_magick20140129-26347-19mg9p8.jpg

### ISSUE THREAD

**Issue by jogaco** [carrierwaveuploader/carrierwave#1305]
Hi,
I am uploading and resizing a lot of images, and from time to time I get this error randomly:

```
Errno::ENOENT: No such file or directory - /tmp/mini_magick20140129-26347-19mg9p8.jpg"
/opt/.../ruby/lib/ruby/1.9.1/fileutils.rb:1370:in `initialize'
/opt/.../ruby/lib/ruby/1.9.1/fileutils.rb:1370:in `open'
/opt/.../ruby/lib/ruby/1.9.1/fileutils.rb:1370:in `copy_file'
/opt/.../ruby/lib/ruby/1.9.1/fileutils.rb:477:in `copy_file'
/opt/.../ruby/lib/ruby/gems/1.9.1/gems/mini_magick-3.5.0/lib/mini_magick.rb:314:in `write'
/opt/.../ruby/lib/ruby/gems/1.9.1/gems/carrierwave-0.9.0/lib/carrierwave/processing/mini_magick.rb:263:in `manipulate!'
/opt/.../ruby/lib/ruby/gems/1.9.1/gems/carrierwave-0.9.0/lib/carrierwave/processing/mini_magick.rb:153:in `resize_to_fit'
/home/.../app/uploaders/image_uploader.rb:71:in `resize'
```

It seems it could be related to this problem: http://stackoverflow.com/a/7956791/345996

**Comment by janosch-x** [comment]
Also see https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Use-a-timestamp-in-file-names
