### ISSUE TITLE
Undefined method `mount_uploaders'

### ISSUE THREAD

**Issue by molayab** [carrierwaveuploader/carrierwave#1551]
Undefined method `mount_uploaders'.

Rails console:
-------

require 'carrierwave' -> return false
require 'carrierwave/orm/activerecord' -> return false

```
2.1.3 :003 > u = Event.new
NoMethodError: undefined method `mount_uploaders' for Event (call 'Event.connection' to establish a connection):Class
	from /Users/molayab/.rvm/gems/ruby-2.1.3/gems/activerecord-4.2.0/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
	from /Users/molayab/Developer/GoOut 2.0/app/models/event.rb:2:in `<class:Event>'
	from /Users/molayab/Developer/GoOut 2.0/app/models/event.rb:1:in `<top (required)>'
	from /Users/molayab/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:457:in `load'
	from /Users/molayab/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:457:in `block in load_file'
	from /Users/molayab/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:647:in `new_constants_in'
	from /Users/molayab/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:456:in `load_file'
	from /Users/molayab/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:354:in `require_or_load'
	from /Users/molayab/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:494:in `load_missing_constant'
	from /Users/molayab/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:184:in `const_missing'
	from (irb):3
	from /Users/molayab/.rvm/gems/ruby-2.1.3/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /Users/molayab/.rvm/gems/ruby-2.1.3/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /Users/molayab/.rvm/gems/ruby-2.1.3/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/molayab/.rvm/gems/ruby-2.1.3/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/molayab/.rvm/gems/ruby-2.1.3/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/molayab/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/molayab/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/molayab/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/molayab/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/molayab/Developer/GoOut 2.0/bin/rails:8:in `<top (required)>'
	from /Users/molayab/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /Users/molayab/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/molayab/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/molayab/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /Users/molayab/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/molayab/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'2.1.3 :004 > 
```

I have installed:
============
 carrierwave 0.10.0
 mini_magick 4.0.2

Application.rb
------------------

```
require File.expand_path('../boot', __FILE__)

require 'rails/all'
require 'carrierwave'
require 'carrierwave/orm/activerecord'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module GoOut20
  class Application < Rails::Application
    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.

    # Set Time.zone default to the specified zone and make Active Record auto-convert to this zone.
    # Run "rake -D time" for a list of tasks for finding time zone names. Default is UTC.
    config.time_zone = 'Bogota'

    # The default locale is :en and all translations from config/locales/*.rb,yml are auto loaded.
    config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}').to_s]
    config.i18n.default_locale = :es

    config.assets.version = '1.0'
    config.assets.paths << Rails.root.join("app", "assets", "fonts")
  end
end
```

event.rb (model)
----------------------

```
class Event < ActiveRecord::Base
  mount_uploaders :images, ImageUploader

  belongs_to :location
  belongs_to :city
  belongs_to :category
end
```

image_uploader.rb (CarrierWave)
--------------------------------------------

```
# encoding: utf-8

class ImageUploader < CarrierWave::Uploader::Base

  # Include RMagick or MiniMagick support:
  # include CarrierWave::RMagick
  include CarrierWave::MiniMagick

  # Choose what kind of storage to use for this uploader:
  storage :file

  process convert: 'png'

  # Override the directory where uploaded files will be stored.
  # This is a sensible default for uploaders that are meant to be mounted:
  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  # Provide a default URL as a default if there hasn't been a file uploaded:
  # def default_url
  #   # For Rails 3.1+ asset pipeline compatibility:
  #   # ActionController::Base.helpers.asset_path("fallback/" + [version_name, "default.png"].compact.join('_'))
  #
  #   "/images/fallback/" + [version_name, "default.png"].compact.join('_')
  # end

  # Process files as they are uploaded:
  # process :scale => [200, 300]
  #
  # def scale(width, height)
  #   # do something
  # end

  # Create different versions of your uploaded files:
  # version :thumb do
  #   process :resize_to_fit => [50, 50]
  # end

  version :thumb do
    #process :resize_to_fill => [180,180]
    process resize_to_fill: [180, 180]
  end

  version :small_thumb do
    process resize_to_fit: [89, 98]
  end

  version :large_thumb do
    process resize_to_fit: [280, 116]
  end

  version :largest_thumb do
    process resize_to_fit: [560, 232]
  end

  # Add a white list of extensions which are allowed to be uploaded.
  # For images you might use something like this:
  def extension_white_list
    %w(jpg jpeg gif png)
  end

  # Override the filename of the uploaded files:
  # Avoid using model.id or version_name here, see uploader/store.rb for details.
  def filename
    "#{SecureRandom.uuid}.#{file.extension}" if original_filename.present?
  end

end
```

**Comment by zlx** [comment]
I think you want to use `mount_uploader` other than `mount_uploaders`

**Comment by AlyOber** [comment]
Hey, I just got this issue too.  Here's what I found.

I was following the examples from the `README.md` but ran into this error when trying the multi-uploads.

I used `bundle` with `gem 'carrierwave', '~> 0.10.0'` to install.  When comparing it to the `0.10.0` version on git, the gem is lacking the `mount_uploaders` function.  You can see this by comparing `/lib/carrierwave/orm/activerecord.rb`.  Odd!

**Comment by bensie** [comment]
`mount_uploaders` is a new feature currently in the master branch, though I'm not sure if it's actually going to ship in 0.11. Stick with `mount_uploader`.

**Comment by AlyOber** [comment]
Might be a good idea to either remove the example from the readme, or make some kind of note.  As it stands, the code doesn't work when following the readme (which says to install it via bundle).

**Comment by bensie** [comment]
Until then, I recommend using the readme from the version you're using:
https://github.com/carrierwaveuploader/carrierwave/tree/v0.10.0

**Comment by nacengineer** [comment]
@AlyOber Why not do a Pull Request? While its good to make a note in this thread, it only takes a few minutes to help the devs out with a PR. :smile:

**Comment by GraySmith00** [comment]
@zix ahh thank you! duh

**Comment by jmccartie** [comment]
FTR, I got this error when adding `react-rails` to my Gemfile.  Once I moved the gem *beneath* carrierwave, the error went away.

¯\_(ツ)_/¯

**Comment by thomasfedb** [comment]
@jmccartie could you open a new issue for this interesting incompatibility please.
