### ISSUE TITLE
Using 'fog-aws' gem Throws uninitialized constant

### ISSUE THREAD

**Issue by morenoh149** [carrierwaveuploader/carrierwave#1608]
Posted https://github.com/fog/fog-aws/issues/77#issuecomment-86103463
Posting here to see if it can be fixed. Either changing the readme to not mention `fog-aws` or fixing whatever the issue is.
```
2015-03-25T09:27:31.876246+00:00 app[web.1]: Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
2015-03-25T09:27:31.876264+00:00 app[web.1]: Recommending WEB_CONCURRENCY=1
2015-03-25T09:27:32.048613+00:00 heroku[worker.1]: State changed from starting to up
2015-03-25T09:27:32.515704+00:00 app[web.1]: I, [2015-03-25T09:27:32.515592 #3]  INFO -- : Refreshing Gem list
2015-03-25T09:27:33.325050+00:00 app[worker.1]: Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
2015-03-25T09:27:33.326484+00:00 app[worker.1]: Recommending WEB_CONCURRENCY=1
2015-03-25T09:27:35.240294+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/configuration.rb:73:in `eval': uninitialized constant CarrierWave::Storage::Fog (NameError)
2015-03-25T09:27:35.240300+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/configuration.rb:73:in `eval'
2015-03-25T09:27:35.240320+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/configuration.rb:73:in `storage'
2015-03-25T09:27:35.240322+00:00 app[web.1]:    from /app/app/uploaders/room_icon_uploader.rb:12:in `<class:RoomIconUploader>'
2015-03-25T09:27:35.240323+00:00 app[web.1]:    from /app/app/uploaders/room_icon_uploader.rb:3:in `<top (required)>'
2015-03-25T09:27:35.240325+00:00 app[web.1]:    from /app/app/models/room.rb:2:in `<class:Room>'
2015-03-25T09:27:35.240326+00:00 app[web.1]:    from /app/app/models/room.rb:1:in `<top (required)>'
2015-03-25T09:27:35.240327+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
2015-03-25T09:27:35.240331+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:471:in `each'
2015-03-25T09:27:35.240332+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:471:in `block in eager_load!'
2015-03-25T09:27:35.240334+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:469:in `each'
2015-03-25T09:27:35.240335+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:469:in `eager_load!'
2015-03-25T09:27:35.240336+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:346:in `eager_load!'
2015-03-25T09:27:35.240338+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application/finisher.rb:56:in `each'
```
previous version of my code https://gist.github.com/morenoh149/a303bb9e823ffc77ac37 I'm now using the `fog` gem.

**Comment by ardecvz** [comment]
Hello,
According to your `Gemfile.lock`, you were using the latest stable version of CarrierWave which doesn't include optimized `fog`'s loading. It's already stated in the [README](https://github.com/carrierwaveuploader/carrierwave/blob/cfaed417bc36443e1e45c4c4c83e879c9f7210c7/README.md#optimized-loading-of-fog): `This functionality is slated for CarrierWave v1.0.0`.

If huge memory consumption really burden your setup, use master version of the gem (beware bugs):
```
gem 'fog-aws'
gem 'carrierwave', github: 'carrierwaveuploader/carrierwave'
```
Or manually require only some parts of `fog`:
```
gem 'fog', require: 'fog/aws'
gem 'carrierwave'
```


Also, please consider using search before reporting next time as your question has already been solved in issues, thanks!

**Comment by joallard** [comment]
So in other words, one gets the choice between a broken stable branch or depending on

```
    fog (1.32.0)
      fog-atmos
      fog-aws (>= 0.6.0)
      fog-brightbox (~> 0.4)
      fog-core (~> 1.32)
      fog-ecloud (= 0.1.1)
      fog-google (>= 0.0.2)
      fog-json
      fog-local
      fog-powerdns (>= 0.1.1)
      fog-profitbricks
      fog-radosgw (>= 0.0.2)
      fog-riakcs
      fog-sakuracloud (>= 0.0.4)
      fog-serverlove
      fog-softlayer
      fog-storm_on_demand
      fog-terremark
      fog-vmfusion
      fog-voxel
      fog-xml (~> 0.1.1)
      ipaddress (~> 0.5)
      nokogiri (~> 1.5, >= 1.5.11)
    fog-atmos (0.1.0)
      fog-core
      fog-xml
    fog-aws (0.6.0)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-brightbox (0.7.2)
      fog-core (~> 1.22)
      fog-json
      inflecto (~> 0.0.2)
    fog-core (1.32.0)
      builder
      excon (~> 0.45)
      formatador (~> 0.2)
      mime-types
      net-scp (~> 1.1)
      net-ssh (>= 2.1.3)
    fog-ecloud (0.1.1)
      fog-core
      fog-xml
    fog-google (0.0.7)
      fog-core
      fog-json
      fog-xml
    fog-json (1.0.2)
      fog-core (~> 1.0)
      multi_json (~> 1.10)
    fog-local (0.2.1)
      fog-core (~> 1.27)
    fog-powerdns (0.1.1)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
    fog-profitbricks (0.0.3)
      fog-core
      fog-xml
      nokogiri
    fog-radosgw (0.0.4)
      fog-core (>= 1.21.0)
      fog-json
      fog-xml (>= 0.0.1)
    fog-riakcs (0.1.0)
      fog-core
      fog-json
      fog-xml
    fog-sakuracloud (1.0.1)
      fog-core
      fog-json
    fog-serverlove (0.1.2)
      fog-core
      fog-json
    fog-softlayer (0.4.7)
      fog-core
      fog-json
    fog-storm_on_demand (0.1.1)
      fog-core
      fog-json
    fog-terremark (0.1.0)
      fog-core
      fog-xml
    fog-vmfusion (0.1.0)
      fission
      fog-core
    fog-voxel (0.1.0)
      fog-core
      fog-xml
    fog-xml (0.1.2)
      fog-core
      nokogiri (~> 1.5, >= 1.5.11)
```

**Comment by joallard** [comment]
Also, your stable branch is broken

**Comment by earnestaddae** [comment]
This approach I just discovered works fine.
Add the following gems to your Gemfile
```ruby
  gem 'net-ssh'
  gem 'fog', '~> 1.36.0'
```
Run bundle, commit your work, then push. Its working for me, I hope it does you too.

**Comment by AlexJuca** [comment]
I had the exact same problem all I had to do was update the gemfile with gem 'fog', require: 'fog/aws'

**Comment by aashish** [comment]
no, It including `gem 'fog', require: 'fog/aws' `did not work for me
