### ISSUE TITLE
configuration: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by joallard** [carrierwaveuploader/carrierwave#1657]
I get the following unfriendly message:

```
/Users/jon/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/configuration.rb:73:in `eval': no implicit conversion of nil into String (TypeError)
	from /Users/jon/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/configuration.rb:73:in `storage'
	from /Users/jon/dev/paperdispatch/app/models/document/storage.rb:11:in `<class:Uploader>'
```

```
module Document::Storage
  extend ActiveSupport::Concern

  included do
    # We use 'data file' because 'file' is used to mean the action of
    # filing documents
    mount_uploader :data_file, Uploader
  end

  class Uploader < CarrierWave::Uploader::Base
    storage :data_file
  end
end
```

Expected: An error message that tells the user where they erred in using the API

**Comment by joallard** [comment]
That said, I used the API like a chump in renaming a field. Sorry, never mind.

**Comment by joallard** [comment]
Actually, maybe `storage` should check what it gets from chumps like me. I'll let you guys decide.

**Comment by eavgerinos** [comment]
I don't find this important, since it's well documented.

Even if CarrierWave checked what symbol you pass there, at the best case you'd get an `ArgumentError` upon initialization.

**Comment by joallard** [comment]
Got it, cheers
