### ISSUE TITLE
"Errno::ENOENT No such file or directory" using fog unless config.delete_tmp_file_after_storage = false

### ISSUE THREAD

**Issue by AndrewMorsillo** [carrierwaveuploader/carrierwave#1662]
Attempting to save an image to S3 using fog fails with

```
Errno::ENOENT (No such file or directory @ rb_sysopen - /path/to/my_app/public/uploads/tmp/1433445809-40745-4105/6_b.jpg):
```

unless I set `config.delete_tmp_file_after_storage = false` in which case it succeeds, but the files are left sitting in the folder. It appears that carrierwave is deleting the tmp file before it is finished using it. I don't want to leave those temp files sitting around or be forced to clean them up with a background job if I don't have to.

Relevant gem versions

```
Using rails 4.2.1
Using carrierwave 0.10.0
Using fog-core 1.30.0
Using fog-aws 0.4.0
```

My config

```
CarrierWave.configure do |config|
    config.storage = :fog
    #config.delete_tmp_file_after_storage = false
    config.fog_credentials = {
        :provider               => 'AWS',   
        :aws_access_key_id      => ENV['AWS_ACCESS_KEY'],      
        :aws_secret_access_key  => ENV['AWS_SECRET_KEY'],       
        :region                 =>  'us-west-1' #provides instant read consistency
    }
    config.fog_directory  = 'myapp-static'    
    config.asset_host       = 'https://static.myapp.com'   
    config.fog_public     = false    
    config.fog_attributes = {'Cache-Control'=>'max-age=315576000'} 
end
```

My uploader

```
class ImageUploader < CarrierWave::Uploader::Base

  def store_dir
    "images/#{secure_token}"
  end

  def secure_token
    if model.image_uuid?
      return model.image_uuid
    else
      model.update_attribute "image_uuid", SecureRandom.uuid
      return model.image_uuid
    end
  end

  def extension_white_list
     %w(jpg jpeg gif png)
  end

end
```

My model

```
class Image < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user
  mount_uploader :image_content, ImageUploader
end
```

My controller action

```
def create
    image = Image.new(:user_id => current_user.id, :username => current_user.username)
    image.image_content = params[:file]
    if image.save
      render :json => {'filelink' => "/images/"+image.id}
      return
    else
      render :json => {error: "failed to save"} 
    end
end
```

**Comment by san** [comment]
Any update on this? I am having the same issue when using the master branch.

**Comment by plribeiro3000** [comment]
I will take a look at this asap. Sorry for the delay.

**Comment by thomasfedb** [comment]
@plribeiro3000 Have you had a chance to look into this issue?

**Comment by plribeiro3000** [comment]
@thomasfedb Sorry. I forgot about this issue. I won't be able to tackle it for next couple of weeks. =s

**Comment by thomasfedb** [comment]
Hey @plribeiro3000, do you think you'd be able to look into this issue this week perhaps?

**Comment by plribeiro3000** [comment]
This seems to be an issue on `fog-aws` side. Could you try to use the latest versions of both `fog-core` and `fog-aws`?

If it still don't work, please open this against `fog-aws` because there will be more people with background on this to help you out then here.

**Comment by plribeiro3000** [comment]
Are you using `activerecord` or mongoid?

**Comment by san** [comment]
FWIW, I was using `activerecord` when I ran into this issue. I have, since then, reverted back to the previous version.

**Comment by plribeiro3000** [comment]
Of which project did you revert back? Carrierwave?

**Comment by san** [comment]
Yes, Carrierwave. I reverted back to the released version instead of the master branch.

**Comment by plribeiro3000** [comment]
Ok. So the problem is on the master branch.

I will take a look later but it might be somewhere around the changes [here](https://github.com/carrierwaveuploader/carrierwave/compare/v0.10.0...master#diff-9bc2a587d40405f3cdedac450914c11e)

**Comment by plribeiro3000** [comment]
Actually, it is not related to any `fog` changes at all.

Need to take a deeper look at [this changes](https://github.com/carrierwaveuploader/carrierwave/compare/v0.10.0...master#diff-6e0806a37c95931f5def08227427cadf)

**Comment by thomasfedb** [comment]
@plribeiro3000 I'm going to leave this with you for now. Thanks for investigating! :sparkles:

**Comment by rsiddle** [comment]
Any luck with this? Stumbed across it when uploading to S3 via Fog.

**Comment by plribeiro3000** [comment]
@rsiddle Sorry. Did not have time to look further yet.
Hopefully this week i will be able to do it.

**Comment by prasannakumargd** [comment]
+1

**Comment by jhelmers-fyber** [comment]
+1

**Comment by cacqw7** [comment]
+1

**Comment by mchicote** [comment]
+1

**Comment by amitstein** [comment]
+1

**Comment by cazador4** [comment]
+1

**Comment by Yanchek99** [comment]
+1

**Comment by dan** [comment]
+1 c'mon, it's been years.

**Comment by rfarese** [comment]
+1

**Comment by relev** [comment]
+1
+1

**Comment by iamemilywing** [comment]
+1

**Comment by ALFmachine** [comment]
+1

**Comment by atz** [comment]
Currently getting this with tests in our rails engine, no S3 involved.  No configuration and just a basic active-record mounted uploader.  

Code is effectively: 
```ruby
OurModel.new(...).uploader.store!(File.open("/path/to/image.jpg"))
```

Trace is:
```
     Errno::ENOENT:
       No such file or directory @ chmod_internal - /Users/atz/repos/hyrax/.internal_test_app/tmp/1498521157-55665-0001-1815/image.jpg
     # /Users/atz/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.1.0/lib/carrierwave/sanitized_file.rb:319:in `chmod'
     # /Users/atz/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.1.0/lib/carrierwave/sanitized_file.rb:319:in `chmod!'
     # /Users/atz/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.1.0/lib/carrierwave/sanitized_file.rb:225:in `copy_to'
     # /Users/atz/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.1.0/lib/carrierwave/uploader/cache.rb:134:in `cache!'
     # /Users/atz/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.1.0/lib/carrierwave/uploader/store.rb:54:in `store!'

```

Why is `new_path` good enough for `mkdir!` and `copy!` but not for `chmod!`?

**Comment by atz** [comment]
Possibly related to an old ticket: #881

**Comment by plribeiro3000** [comment]
cc/ @carrierwaveuploader/carrierwave-core  Is this still an issue? 

Is rather old and i'm afraid i don't have all the knowledge required for this issue.

Maybe someone else can tackle it?

Thanks!

**Comment by gabriel-alcantara** [comment]
+1

**Comment by therealrodk** [comment]
This is still an issue. I am trying to follow the docs for the sitemap-generator gem, [here](https://github.com/kjvarga/sitemap_generator/wiki/Generate-Sitemaps-on-read-only-filesystems-like-Heroku), under the heading "Using CarrierWave."

```rake sitemap:refresh
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/Daddy/Sites/pbb/sample_app/tmp/1520628594-48486-0001-9974/sitemap1.xml.gz
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.2.2/lib/carrierwave/sanitized_file.rb:163:in `initialize'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.2.2/lib/carrierwave/sanitized_file.rb:163:in `open'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.2.2/lib/carrierwave/sanitized_file.rb:163:in `read'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.2.2/lib/carrierwave/storage/fog.rb:316:in `store'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.2.2/lib/carrierwave/storage/fog.rb:78:in `store!'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.2.2/lib/carrierwave/uploader/store.rb:57:in `block in store!'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.2.2/lib/carrierwave/uploader/callbacks.rb:15:in `with_callbacks'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.2.2/lib/carrierwave/uploader/store.rb:56:in `store!'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/sitemap_generator-6.0.1/lib/sitemap_generator/adapters/wave_adapter.rb:18:in `write'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/sitemap_generator-6.0.1/lib/sitemap_generator/sitemap_location.rb:166:in `write'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/sitemap_generator-6.0.1/lib/sitemap_generator/builder/sitemap_file.rb:139:in `write'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/sitemap_generator-6.0.1/lib/sitemap_generator/builder/sitemap_index_file.rb:138:in `write_first_sitemap'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/sitemap_generator-6.0.1/lib/sitemap_generator/builder/sitemap_index_file.rb:104:in `finalize!'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/sitemap_generator-6.0.1/lib/sitemap_generator/link_set.rb:468:in `finalize_sitemap_index!'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/sitemap_generator-6.0.1/lib/sitemap_generator/link_set.rb:339:in `finalize!'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/sitemap_generator-6.0.1/lib/sitemap_generator/link_set.rb:41:in `create'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/sitemap_generator-6.0.1/lib/sitemap_generator.rb:41:in `method_missing'
/Users/Daddy/Sites/pbb/sample_app/config/sitemap.rb:8:in `run'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/sitemap_generator-6.0.1/lib/sitemap_generator/interpreter.rb:78:in `instance_eval'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/sitemap_generator-6.0.1/lib/sitemap_generator/interpreter.rb:78:in `run'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/sitemap_generator-6.0.1/lib/sitemap_generator/tasks.rb:51:in `block (2 levels) in <top (required)>'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/Users/Daddy/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/task.rb:217:in `block in invoke_prerequisites'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/task.rb:215:in `each'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/task.rb:215:in `invoke_prerequisites'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/Users/Daddy/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/Users/Daddy/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/Users/Daddy/.rvm/gems/ruby-2.4.1/bin/rake:23:in `load'
/Users/Daddy/.rvm/gems/ruby-2.4.1/bin/rake:23:in `<main>'
/Users/Daddy/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/Users/Daddy/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'```

I tried `config.delete_tmp_file_after_storage = false` but it didn't help.

So, +1, I guess?

**Comment by AndreFSilveira** [comment]
+1

**Comment by mshibuya** [comment]
I suppose people having this issue should have something bad in their code(for @AndrewMorsillo 's case, calling `#update_attribute` is bad because it will invoke another update process, amid of update).
Just `+1` is not enough, please paste full stack trace and your code(model and uploader), then I'll look into them.

**Comment by crwang** [comment]
I also got this error when I recently upgraded with no changes and using the standard setup. 

I did notice that the error was something like this:

Errno::ENOENT: No such file or directory @ rb_sysopen - /app/public/uploads/tmp/old-filename.jpg

and that the file was uploaded to s3 with the my overridden filename in the model if that helps at all.

But, basically, it seemed to upload the smallest resized image (first in my version) and then died with the "Errno::ENOENT No such file or directory"

I did add the `config.delete_tmp_file_after_storage = false` to the initializer and that fixed the issue for me, for now.  :)

Here's the relevant uploader code:

```
class AvatarUploader < CarrierWave::Uploader::Base
  include CarrierWave::RMagick

  storage :fog
  def store_dir
    "images/#{model.class.to_s.pluralize.underscore}/#{model.id}/#{mounted_as}"
  end

  def base_store_dir
    "images/#{model.class.to_s.pluralize.underscore}/#{model.id}/#{mounted_as}"
  end

  def filename
    unless model.avatar.file.nil?
      if original_filename
        "#{model.slug}.#{model.avatar.file.extension}" if original_filename
      else
        File.basename path
      end
    end
  end

  process resize_to_limit: [2000, 2000]

  version :v64 do
    def store_dir
      File.join(base_store_dir, '64')
    end

    def full_filename(for_file)
      for_file.downcase
    end
    process resize_to_limit: [64, 64]
  end

  version :v160 do
    def store_dir
      File.join(base_store_dir, '160')
    end

    def full_filename(for_file)
      for_file.downcase
    end
    process resize_to_limit: [160, 160]
  end
  
  # And several more versions here
```

And the relevant model code:
```
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
```

**Comment by mshibuya** [comment]
@crwang Your issue is version file name collision.
CarrierWave processes version files on cache phase, so processed files reside in single directory given by `cache_dir`. If they have the same name, they'll get overwritten. But `#store` thinks the cached file for each version exists, so the `Errno::ENOENT` error.

Instead of changing `store_dir` in versions, you can go this way:

```ruby
  version :v64 do
    def full_filename(for_file)
      File.join('64', for_file.downcase)
    end
    process resize_to_limit: [64, 64]
  end
```

**Comment by crwang** [comment]
Awesome, thanks I'll give this a try in the next day or so! Thanks!

**Comment by crwang** [comment]
Thanks @mshibuya! Totally makes sense and I updated the code and things work great for me now.  👍
