### ISSUE TITLE
Remove file is not working on update

### ISSUE THREAD

**Issue by danicuki** [carrierwaveuploader/carrierwave#1694]
I have a model with file upload on property named `uploaded_track`

When I try to remove a previously uploaded file with this command:
```
myObject.update({"remove_uploaded_track"=> "1"})
```

I get an error:
```
Fog::Storage::Rackspace::NotFound: [HTTP 404 | tx7ff2a86278a847f3ad1d8-00559443f1iad3] resource not found in iad region
	from /Users/devstation2/.rvm/gems/ruby-2.0.0-p353/gems/fog-1.31.0/lib/fog/rackspace/storage.rb:446:in `rescue in request'
	from /Users/devstation2/.rvm/gems/ruby-2.0.0-p353/gems/fog-1.31.0/lib/fog/rackspace/storage.rb:444:in `request'
	from /Users/devstation2/.rvm/gems/ruby-2.0.0-p353/gems/fog-1.31.0/lib/fog/rackspace/requests/storage/delete_object.rb:15:in `delete_object'
	from /Users/devstation2/.rvm/gems/ruby-2.0.0-p353/gems/fog-1.31.0/lib/fog/rackspace/models/storage/file.rb:120:in `destroy'
	from /Users/devstation2/.rvm/gems/ruby-2.0.0-p353/gems/carrierwave-0.10.0/lib/carrierwave/storage/fog.rb:187:in `delete'
	from /Users/devstation2/.rvm/gems/ruby-2.0.0-p353/gems/carrierwave-0.10.0/lib/carrierwave/uploader/remove.rb:15:in `block in remove!'
	from /Users/devstation2/.rvm/gems/ruby-2.0.0-p353/gems/carrierwave-0.10.0/lib/carrierwave/uploader/callbacks.rb:17:in `with_callbacks'
	from /Users/devstation2/.rvm/gems/ruby-2.0.0-p353/gems/carrierwave-0.10.0/lib/carrierwave/uploader/remove.rb:14:in `remove!'
	from /Users/devstation2/.rvm/gems/ruby-2.0.0-p353/gems/carrierwave-0.10.0/lib/carrierwave/mount.rb:244:in `remove_previously_stored_uploaded_track'
	from /Users/devstation2/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'
	from /Users/devstation2/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:228:in `call'
	from /Users/devstation2/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:228:in `block in halting_and_conditional'
	from /Users/devstation2/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:506:in `call'
	from /Users/devstation2/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:506:in `block in call'
	from /Users/devstation2/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:506:in `each'
	from /Users/devstation2/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:506:in `call'
```

It looks like it is trying to delete the file twice. I observed that the file was actually removed from my Rackspace account, but the reference to it in Rails model is still there.

**Comment by bensie** [comment]
This appears to be an issue on the Fog side of things. Perhaps Fog isn't properly handling the initial response that the file was deleted.
