### ISSUE TITLE
Error while generating an uploader

### ISSUE THREAD

**Issue by VincentVanGoat** [carrierwaveuploader/carrierwave#1723]
Hey. I am trying to get users on my website to upload files on a google cloud bucket and for this, I am using Carrierwave. 

When I try to use the command: 

rails g uploader file

I get this error: 

c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/configuration.rb:127:in `cli': ImageMagick/GraphicsMagick is not installed (MiniMagick::Error)
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick.rb:37:in `graphicsmagick?'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/tool.rb:111:in `executable'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/tool.rb:95:in `command'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/tool.rb:80:in `call'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/tool.rb:252:in `cli_options'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/tool.rb:205:in `reload_methods'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/tool.rb:191:in `initialize'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/tool.rb:21:in `new'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/tool.rb:21:in `inherited'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/tool/animate.rb:6:in `<class:Tool>'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/tool/animate.rb:2:in `<module:MiniMagick>'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/tool/animate.rb:1:in `<top (required)>'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/tool.rb:264:in `require'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/tool.rb:264:in `<top (required)>'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick.rb:54:in `require'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick.rb:54:in `<top (required)>'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:76:in `require'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:72:in `each'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:72:in `block in require'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:61:in `each'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:61:in `require'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler.rb:134:in `require'
        from c:/Users/Kanishka/googleprediction/prediction-app/config/application.rb:7:in `<top (required)>'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:141:in `require'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:141:in `require_application_and_environment!'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:128:in `generate_or_destroy'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:50:in `generate'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'

Please help!

**Comment by VincentVanGoat** [comment]
This was fixed by changing the version of carrierwave from 4.2.10 to 4.2.7.
