### ISSUE TITLE
Theres no mount_uploaders on version 0.10.0?

### ISSUE THREAD

**Issue by xdougx** [carrierwaveuploader/carrierwave#1748]
Got this error `undefined method 'mount_uploaders' `
with this backtrace:
```
	from /Users/douglas/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
	from /Users/douglas/workspace/kanamobi/promoters/app/models/promoter.rb:15:in `<class:Promoter>'
	from /Users/douglas/workspace/kanamobi/promoters/app/models/promoter.rb:1:in `<top (required)>'
	from /Users/douglas/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:457:in `load'
	from /Users/douglas/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:457:in `block in load_file'
	from /Users/douglas/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:647:in `new_constants_in'
	from /Users/douglas/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:456:in `load_file'
	from /Users/douglas/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:354:in `require_or_load'
	from /Users/douglas/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:494:in `load_missing_constant'
	from /Users/douglas/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:184:in `const_missing'
	from (irb):1
	from /Users/douglas/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in `start'
	from /Users/douglas/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
	from /Users/douglas/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/douglas/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/douglas/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/douglas/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/douglas/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/douglas/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/douglas/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/douglas/workspace/kanamobi/promoters/bin/rails:8:in `<top (required)>'
	from /Users/douglas/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /Users/douglas/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/douglas/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/douglas/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /Users/douglas/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/douglas/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'2.2.2 :002 > 
```
With this class:
```ruby
class Promoter < ActiveRecord::Base
  mount_uploaders :photos, AlbumUploader
end
```
Version 0.10.0 has no support for it?
Which version i need to use?

**Comment by eavgerinos** [comment]
@xdougx Master branch. The README at master refers to the master branch only.

For 0.10.0 see [here](https://github.com/carrierwaveuploader/carrierwave/tree/v0.10.0)

**Comment by xdougx** [comment]
If I need to user
gem 'carrierwave', github: 'carrierwaveuploader/carrierwave', branch: 'master'
is this the right way?
