### ISSUE TITLE
Changing storage from :file to :fog

### ISSUE THREAD

**Issue by george1minus1** [carrierwaveuploader/carrierwave#1776]
Hi Guys,

I've been using carrierwave hassle free for some time now, so thank for a great gem.

As is traditional the customer requirements have changed, and now all storage is to be on S3. I've got that work fine. My question is, how do I get existing file based uploaders migrated to a fog based version.

I've tried using `recreate_versions!` but I get the following error

```
NoMethodError: undefined method `body' for nil:NilClass
	from /Users/george/.rvm/gems/ruby-2.1.5/gems/carrierwave-0.10.0/lib/carrierwave/storage/fog.rb:228:in `read'
	from /Users/george/.rvm/gems/ruby-2.1.5/gems/carrierwave-0.10.0/lib/carrierwave/uploader/cache.rb:77:in `sanitized_file'
	from /Users/george/.rvm/gems/ruby-2.1.5/gems/carrierwave-0.10.0/lib/carrierwave/uploader/cache.rb:116:in `cache!'
	from /Users/george/.rvm/gems/ruby-2.1.5/gems/carrierwave-0.10.0/lib/carrierwave/uploader/versions.rb:226:in `recreate_versions!'
	from (irb):1
	from /Users/george/.rvm/gems/ruby-2.1.5/gems/railties-4.1.4/lib/rails/commands/console.rb:90:in `start'
	from /Users/george/.rvm/gems/ruby-2.1.5/gems/railties-4.1.4/lib/rails/commands/console.rb:9:in `start'
	from /Users/george/.rvm/gems/ruby-2.1.5/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /Users/george/.rvm/gems/ruby-2.1.5/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/george/.rvm/gems/ruby-2.1.5/gems/railties-4.1.4/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/george/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
	from /Users/george/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `block in require'
	from /Users/george/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/george/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
	from /Users/george/Development/babyforest/bin/rails:8:in `<top (required)>'
	from /Users/george/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:241:in `load'
	from /Users/george/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:241:in `block in load'
	from /Users/george/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/george/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:241:in `load'
	from /Users/george/.rvm/gems/ruby-2.1.5/gems/spring-1.2.0/lib/spring/commands/rails.rb:6:in `call'
	from /Users/george/.rvm/gems/ruby-2.1.5/gems/spring-1.2.0/lib/spring/command_wrapper.rb:38:in `call'
	from /Users/george/.rvm/gems/ruby-2.1.5/gems/spring-1.2.0/lib/spring/application.rb:183:in `block in serve'
	from /Users/george/.rvm/gems/ruby-2.1.5/gems/spring-1.2.0/lib/spring/application.rb:156:in `fork'
	from /Users/george/.rvm/gems/ruby-2.1.5/gems/spring-1.2.0/lib/spring/application.rb:156:in `serve'
	from /Users/george/.rvm/gems/ruby-2.1.5/gems/spring-1.2.0/lib/spring/application.rb:131:in `block in run'
	from /Users/george/.rvm/gems/ruby-2.1.5/gems/spring-1.2.0/lib/spring/application.rb:125:in `loop'
	from /Users/george/.rvm/gems/ruby-2.1.5/gems/spring-1.2.0/lib/spring/application.rb:125:in `run'
	from /Users/george/.rvm/gems/ruby-2.1.5/gems/spring-1.2.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/george/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/george/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

Any suggestions on how to move forward with this would be awesome!

Cheers,
George

**Comment by thomasfedb** [comment]
Are you able to provide the code that produces this error?

**Comment by thomasfedb** [comment]
Closing due to inactivity.

**Comment by zzet** [comment]
same error

```
NoMethodError: undefined method `body' for nil:NilClass
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/storage/fog.rb:228:in `read'
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/cache.rb:77:in `sanitized_file'
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/cache.rb:116:in `cache!'
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/versions.rb:226:in `recreate_versions!'
	from /srv/apps/project/releases/20160303154307/app/models/user.rb:285:in `crop_avatar'
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:228:in `call'
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:228:in `block in halting_and_conditional'
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:506:in `call'
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:506:in `block in call'
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:506:in `each'
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:506:in `call'
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:778:in `_run_update_callbacks'
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/callbacks.rb:310:in `_update_record'
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/timestamp.rb:70:in `_update_record'
... 21 levels...
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/persistence.rb:252:in `block in update'
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:220:in `transaction'
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/persistence.rb:250:in `update'
	from (irb):5
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/console.rb:110:in `start'
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/console.rb:9:in `start'
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /srv/apps/project/releases/20160303154307/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
```
