### ISSUE TITLE
Multiple File Upload from a local file

### ISSUE THREAD

**Issue by popup-user** [carrierwaveuploader/carrierwave#1791]
I see how to automate a single file upload here - which is nice:
https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-%22Upload%22-from-a-local-file

But how would I automate multiple file uploads for a record when using "Multiple file uploads" with e.g:
```ruby
class User < ActiveRecord::Base
  mount_uploaders :avatars, AvatarUploader
end
```

**Comment by thomasfedb** [comment]
Have you tried anything?

```ruby
restaurant = Restaurant.create!(name: "McDonald's")
restaurant.logos << Rails.root.join("db/images/mcdonalds_logo.png").open
restaurant.save!
```

**Comment by popup-user** [comment]
So this is what I've tried:

```ruby
# the create! works, no problem:
space = Space.create!(id: 1, ref_id: 1, country: 'United States', city: 'New York',
	sf_currency_iso_code: 'EUR', sf_space_status: 'Offline')
space.photos << Pathname.new("/Users/n/Downloads/space_sample_1.jpg").open
space.photos << Pathname.new("/Users/n/Downloads/space_sample_2.jpg").open
space.save!
```
it works until the save!, when I get:
```
> space.save!
   (0.4ms)  BEGIN
  Space Exists (0.7ms)  SELECT  1 AS one FROM "spaces" WHERE ("spaces"."ref_id" = 1 AND "spaces"."id" != 12964) LIMIT 1
   (0.4ms)  ROLLBACK
NoMethodError: undefined method `identifier' for #<File:/Users/n/Downloads/space_sample_1.jpg>
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/bundler/gems/carrierwave-5217412e56ca/lib/carrierwave/mounter.rb:24:in `map'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/bundler/gems/carrierwave-5217412e56ca/lib/carrierwave/mounter.rb:24:in `identifiers'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/bundler/gems/carrierwave-5217412e56ca/lib/carrierwave/mount.rb:327:in `write_photos_identifier'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:432:in `block in make_lambda'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:164:in `call'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:164:in `block in halting'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `call'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `block in call'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `each'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `call'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activerecord-4.2.4/lib/active_record/callbacks.rb:302:in `create_or_update'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activerecord-4.2.4/lib/active_record/persistence.rb:142:in `save!'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activerecord-4.2.4/lib/active_record/validations.rb:43:in `save!'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activerecord-4.2.4/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activerecord-4.2.4/lib/active_record/transactions.rb:291:in `block in save!'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activerecord-4.2.4/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activerecord-4.2.4/lib/active_record/transactions.rb:220:in `transaction'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activerecord-4.2.4/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/activerecord-4.2.4/lib/active_record/transactions.rb:291:in `save!'
	from (irb):8
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in `start'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/n/.rvm/gems/ruby-2.2.3@poprails/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
```

**Comment by popup-user** [comment]
I should also mention that my datatype is jsonb in postgresql 9.4! Perhaps I should switch to the Array datatype..

I get the same error when using:
```ruby
space = Space.create!( ref_id: 1, country: 'United States', city: 'New York',
    sf_currency_iso_code: 'EUR', sf_space_status: 'Offline')
space.photos[0] = Pathname.new("/Users/n/Downloads/space_sample_1.jpg").open
space.save!

#or even just, 
space = Space.create!( ref_id: 1, country: 'United States', city: 'New York',
    sf_currency_iso_code: 'EUR', sf_space_status: 'Offline')
space.photos[0] = Pathname.new("/Users/n/Downloads/space_sample_1.jpg").open
space.save!



```

**Comment by thomasfedb** [comment]
Is this use-case supported @bensie?

**Comment by thomasfedb** [comment]
@popup-user can you please try:

```ruby
space.photos = [
  Pathname.new("/Users/n/Downloads/space_sample_1.jpg").open,
  Pathname.new("/Users/n/Downloads/space_sample_2.jpg").open
]
```

**Comment by nathanpop** [comment]
A great @thomasfedb ! It worked! I had switched to the postgresql Array type. Thanks so much!

**Comment by nathanpop** [comment]
I updated the wiki: https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-%22Upload%22-from-a-local-file . Cheers.
