### ISSUE TITLE
Undefined method 'mount_uploader' when adding `react-rails`

### ISSUE THREAD

**Issue by jmccartie** [carrierwaveuploader/carrierwave#1852]
If I add the `react-rails` Gem above carrierwave, I get "Undefined method `mount_uploader` whenever I try to start Rails

```
/Users/jmccartie/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing': undefined method `mount_uploader' for Photo (call 'Photo.connection' to establish a connection):Class (NoMethodError)
	from /Users/jmccartie/Code/campendium/app/models/photo.rb:17:in `<class:Photo>'
	from /Users/jmccartie/Code/campendium/app/models/photo.rb:1:in `<top (required)>'
	from /Users/jmccartie/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:457:in `load'
	from /Users/jmccartie/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:457:in `block in load_file'
	from /Users/jmccartie/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:647:in `new_constants_in'
	from /Users/jmccartie/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:456:in `load_file'
	from /Users/jmccartie/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:354:in `require_or_load'
	from /Users/jmccartie/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:494:in `load_missing_constant'
	from /Users/jmccartie/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:184:in `const_missing'
	from /Users/jmccartie/Code/campendium/config/initializers/rails_admin.rb:48:in `block in <top (required)>'
	from /Users/jmccartie/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rails_admin-0.6.4/lib/rails_admin.rb:30:in `call'
	from /Users/jmccartie/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rails_admin-0.6.4/lib/rails_admin.rb:30:in `config'
	from /Users/jmccartie/Code/campendium/config/initializers/rails_admin.rb:4:in `<top (required)>'
```

But works fine when I move react-rails beneath `carrierwave` in the Gemfile.

Removing `rails_admin` also fixes the issue. Sooooooo ... much complicate. :smile:

**Comment by thomasfedb** [comment]
Could you provide your Gemfile that produces the error.

**Comment by jmccartie** [comment]
```
gem 'react-rails'
gem 'carrierwave'
gem 'rails_admin'
```

**Comment by jmccartie** [comment]
As a note, I fixed this by moving `react-rails` to the bottom, so this is not an urgent issue for me.  I'm submitting by request in #1551 

Let me know how else I can help...

**Comment by thomasfedb** [comment]
Do you have Rails in your Gemfile?

**Comment by jmccartie** [comment]
@thomasfedb Yeah, sorry. The whole thing is massive (this is a legacy app I'm rescuing for a client). Rails is at 4.2.5.1

**Comment by thomasfedb** [comment]
Is Rails the first entry in the Gemfile? Are you at liberty to Gist the Gemfile?

**Comment by jmccartie** [comment]
@thomasfedb I'm not at liberty to share the entire file.  Here's the top:

```
source 'https://rubygems.org'
ruby '2.2.3'

gem 'rails', '4.2.5.1'

# (the middle)

gem 'react-rails'
gem 'rails_admin', '0.6.4'
gem "active_model_serializers"

# (more stuff)

gem "geocoder", :git => "git://github.com/alexreisner/geocoder.git"
gem 'carrierwave'
gem 'fog', '~> 1.37.0'

# (more stuff)
```

**Comment by thomasfedb** [comment]
Thanks @jmccartie

**Comment by mehlah** [comment]
This looks like to be a react-rails issue currently discussed https://github.com/reactjs/react-rails/issues/326
I'll probably submit a fix there later today 😇
