### ISSUE TITLE
How to get the width of tmp file when the filename is Chinese?

### ISSUE THREAD

**Issue by hxx** [carrierwaveuploader/carrierwave#1859]
I want to scale the image when the width of the image is larger then a special value

``` ruby
  process :scale => [730, 600]
  #
  def scale(width, height)
    if self.width > width
      resize_to_fit(width, height)
    end
  end
```

when the image's filename is Chinese, I can get the size of the tmp file normally, but I can't get the width of the tmp file.

the tmp file with directory is
 "../tmp/1454320445-54102-8395/图片.jpg",

but when I try to get the width of the image, it will say that no file named 
"../tmp/1454320445-54102-8395/%E5%9B%BE%E7%89%87.jpg"

How can I get the width of the tmp file? 

the image paramter:

``` ruby
"image"=>#<ActionDispatch::Http::UploadedFile:0x007fda35d07d40 @tempfile=#<Tempfile:/var/folders/_x/xxb5nb8x3056l48sh7vz126c0000gn/T/RackMultipart20160201-54102-12i73k8.jpg>, @original_filename="图片.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"images[]\"; filename=\"\xE5\x9B\xBE\xE7\x89\x87.jpg\"\r\nContent-Type: image/jpeg\r\n">
```

the error:

``` ruby
"Errno::ENOENT (No such file or directory @ rb_sysopen ../tmp/1454320445-54102-8395/%E5%9B%BE%E7%89%87.jpg"
```

**Comment by thomasfedb** [comment]
Can you please provide the full stack trace.

**Comment by hxx** [comment]
my **image_uploader.rb** is
```ruby
# encoding: utf-8

class ImageUploader < CarrierWave::Uploader::Base

  # Include RMagick or MiniMagick support:
  # include CarrierWave::RMagick
  include CarrierWave::MiniMagick

  # Choose what kind of storage to use for this uploader:
  storage :file
  # storage :fog

  # Override the directory where uploaded files will be stored.
  # This is a sensible default for uploaders that are meant to be mounted:
  def store_dir
    "uploads/#{mounted_as}/"
  end

  # Provide a default URL as a default if there hasn't been a file uploaded:
  # def default_url
  #   # For Rails 3.1+ asset pipeline compatibility:
  #   # ActionController::Base.helpers.asset_path("fallback/" + [version_name, "default.png"].compact.join('_'))
  #
  #   "/images/fallback/" + [version_name, "default.png"].compact.join('_')
  # end

  # Process files as they are uploaded:
  process :scale => [730, 600]
  #
  def scale(width, height)
    if self.width > width
      resize_to_fit(width, height)
    end
  end
  # process resize_to_fill: [100, 100]

  # Create different versions of your uploaded files:
  # version :thumb do
  #   process :resize_to_fit => [50, 50]
  # end


  # Add a white list of extensions which are allowed to be uploaded.
  # For images you might use something like this:
  def extension_white_list
    %w(jpg jpeg gif png)
  end
  #
  # Override the filename of the uploaded files:
  # Avoid using model.id or version_name here, see uploader/store.rb for details.
  def filename
    "image-#{DateTime.now.to_datetime.to_i}-#{original_filename}" if original_filename
  end

end
```

when I upload the image named "图片.jpg", and here is the full stack trace 

```
Started POST "/images/multiple_upload/" for ::1 at 2016-02-02 18:09:44 +0800
Processing by ImagesController#multiple_upload as */*
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"VS+70Gj3wxj8USKeYSAH2IMET2v8oxPcLhPhEkHODHOoVODQNioaVf5jDhXjz1aIuSTykDje+VRBQF1puKU50w==", "blog"=>{"title"=>"", "tag_list"=>"", "poster_cache"=>"", "remove_poster"=>"0"}, "editormd-markdown-doc"=>"", "images"=>[#<ActionDispatch::Http::UploadedFile:0x007ff6bbc5bc28 @tempfile=#<Tempfile:/var/folders/_x/xxb5nb8x3056l48sh7vz126c0000gn/T/RackMultipart20160202-58177-h0xz8e.jpg>, @original_filename="图片.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"images[]\"; filename=\"\xE5\x9B\xBE\xE7\x89\x87.jpg\"\r\nContent-Type: image/jpeg\r\n">]}
Completed 500 Internal Server Error in 24ms (ActiveRecord: 1.3ms)

Errno::ENOENT (No such file or directory @ rb_sysopen - /Users/hxx/myApp/tmp/1454407785-58177-7014/%E5%9B%BE%E7%89%87.jpg):
  app/uploaders/image_uploader.rb:31:in `scale'
  app/controllers/images_controller.rb:20:in `multiple_upload'


  Rendered /Users/hxx/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/_source.erb (4.5ms)
  Rendered /Users/hxx/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (1.0ms)
  Rendered /Users/hxx/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb (2.6ms)
  Rendered /Users/hxx/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/diagnostics.text.erb (57.2ms)
Cannot render console with content type multipart/form-dataAllowed content types: [#<Mime::Type:0x007ff6b6c170a0 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html">, #<Mime::Type:0x007ff6b6c16d58 @synonyms=[], @symbol=:text, @string="text/plain">, #<Mime::Type:0x007ff6b7473438 @synonyms=[], @symbol=:url_encoded_form, @string="application/x-www-form-urlencoded">]
```

It looks like the filename of image is "**\xE5\x9B\xBE\xE7\x89\x87.jpg**", but it will look for the image named "**%E5%9B%BE%E7%89%87.jpg**"

and when I upload the image named "**image.jpg**", it success. 
the filename of the image is "**image.jpg**", and it will look for the image named "**image.jpg**"
```
Started POST "/images/multiple_upload/" for ::1 at 2016-02-02 18:13:04 +0800
Processing by ImagesController#multiple_upload as */*
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"VS+70Gj3wxj8USKeYSAH2IMET2v8oxPcLhPhEkHODHOoVODQNioaVf5jDhXjz1aIuSTykDje+VRBQF1puKU50w==", "blog"=>{"title"=>"", "tag_list"=>"", "poster_cache"=>"", "remove_poster"=>"0"}, "editormd-markdown-doc"=>"", "images"=>[#<ActionDispatch::Http::UploadedFile:0x007ff6ba972878 @tempfile=#<Tempfile:/var/folders/_x/xxb5nb8x3056l48sh7vz126c0000gn/T/RackMultipart20160202-58177-3u03nq.jpg>, @original_filename="image.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"images[]\"; filename=\"image.jpg\"\r\nContent-Type: image/jpeg\r\n">]}
   (0.2ms)  BEGIN
  SQL (10.9ms)  INSERT INTO "images" ("images", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["images", "[\"image-1454407984-image.jpg\"]"], ["created_at", "2016-02-02 10:13:04.517928"], ["updated_at", "2016-02-02 10:13:04.517928"]]
   (6.0ms)  COMMIT
Completed 200 OK in 102ms (Views: 0.9ms | ActiveRecord: 17.9ms)
```

@thomasfedb thanks.

**Comment by thomasfedb** [comment]
Right, so this is an escaping issue. It would appear that we're inconsistent with escaping of non-`\w` filenames somewhere.

**Comment by thomasfedb** [comment]
For clarity @hxx, what version of CarrierWave are you using?

**Comment by hxx** [comment]
@thomasfedb I am using the master branch to enable multiple file uploads.

in my gemfile:

```ruby
gem 'carrierwave', github: 'carrierwaveuploader/carrierwave'
```

gemfile.lock:
```ruby
GIT
  remote: git://github.com/carrierwaveuploader/carrierwave.git
  revision: e3acabb512cb55b683b6d74a63db0723f06df091
  specs:
    carrierwave (0.10.0)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      json (>= 1.7)
      mime-types (>= 1.16)
```

**Comment by thomasfedb** [comment]
Thanks @hxx. Can you test against 4aec9824 and let me know if that changes anything.

**Comment by hxx** [comment]
@thomasfedb  I tested https://github.com/carrierwaveuploader/carrierwave/commit/4aec9824cba9436ebf368899ad3b5cd0f609d354 and https://github.com/carrierwaveuploader/carrierwave/commit/b742d7fc1d095e7a2541e27bf281fd48fc142715, it not works.

**Comment by hxx** [comment]
https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/processing/mini_magick.rb#L319-L325

the **url** of this image is 
"/Users/hxx/myApp/tmp/1454428608-63558-0001-5926/%E5%9B%BE%E7%89%87.jpg"

and the **current_path** of this image is 
"/Users/hxx/myApp/tmp/1454428608-63558-0001-5926/图片.jpg"
(I can find this image with the current_path)

Is that necessary to open the image with the **url** ?
Maybe we can just open the image with the  **current_path** ?

**Comment by thomasfedb** [comment]
My understanding (though perhaps flawed) is that the `url` should never be used against the local filesystem, and should only be used as an identifier in URLs.

**Comment by s-lee-kwong** [comment]
I am currently having a similar problem in that I am trying to upload a file with chinese characters in the filename but it results in 3041771_772出货检查.pdf = 3041771_772____.pdf. I know this is a sanitization problem but I was wondering how would I keep the chinese characters there in the filename.

Thanks

**Comment by sarojkh** [comment]
@s-lee-kwong There is a solution recommended in the wiki, but it doesn't have desired outcome. See #1835 .

**Comment by mshibuya** [comment]
This is correct, so the cause is a usage problem.
https://github.com/carrierwaveuploader/carrierwave/issues/1859#issuecomment-178692830
