### ISSUE TITLE
Versioning & converting image with uppercase extension errors "same file" OSX

### ISSUE THREAD

**Issue by raldred** [carrierwaveuploader/carrierwave#1924]
I have my version (thumb) set to process and convert to jpg.
This works fine unless the user uploads an image that's already a jpg but with an uppercase extension JPG.

I'm running Ruby 2.2.2, Rails 4.2.4 & Carrierwave as of 49fdad1ec6ca

It raises the following error:

```
same file: /Users/robaldred/Sites/oldknows/tmp/1461167591-8459-6983/thumb/test_image.JPG
and /Users/robaldred/Sites/oldknows/tmp/1461167591-8459-6983/thumb/test_image.jpg

/Users/robaldred/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:1569:in `block in fu_each_src_dest'
/Users/robaldred/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:1586:in `fu_each_src_dest0'
/Users/robaldred/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:1568:in `fu_each_src_dest'
/Users/robaldred/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:516:in `mv'
/Users/robaldred/.rvm/gems/ruby-2.2.2/bundler/gems/carrierwave-49fdad1ec6ca/lib/carrierwave/sanitized_file.rb:189:in `move_to'
/Users/robaldred/.rvm/gems/ruby-2.2.2/bundler/gems/carrierwave-49fdad1ec6ca/lib/carrierwave/processing/rmagick.rb:331:in `manipulate!'
/Users/robaldred/.rvm/gems/ruby-2.2.2/bundler/gems/carrierwave-49fdad1ec6ca/lib/carrierwave/processing/rmagick.rb:118:in `convert'
/Users/robaldred/.rvm/gems/ruby-2.2.2/bundler/gems/carrierwave-49fdad1ec6ca/lib/carrierwave/uploader/processing.rb:84:in `block in process!'
/Users/robaldred/.rvm/gems/ruby-2.2.2/bundler/gems/carrierwave-49fdad1ec6ca/lib/carrierwave/uploader/processing.rb:76:in `each'
/Users/robaldred/.rvm/gems/ruby-2.2.2/bundler/gems/carrierwave-49fdad1ec6ca/lib/carrierwave/uploader/processing.rb:76:in `process!'
/Users/robaldred/.rvm/gems/ruby-2.2.2/bundler/gems/carrierwave-49fdad1ec6ca/lib/carrierwave/uploader/callbacks.rb:16:in `block in with_callbacks'
/Users/robaldred/.rvm/gems/ruby-2.2.2/bundler/gems/carrierwave-49fdad1ec6ca/lib/carrierwave/uploader/callbacks.rb:16:in `each'
/Users/robaldred/.rvm/gems/ruby-2.2.2/bundler/gems/carrierwave-49fdad1ec6ca/lib/carrierwave/uploader/callbacks.rb:16:in `with_callbacks'
/Users/robaldred/.rvm/gems/ruby-2.2.2/bundler/gems/carrierwave-49fdad1ec6ca/lib/carrierwave/uploader/cache.rb:127:in `cache!'
/Users/robaldred/.rvm/gems/ruby-2.2.2/bundler/gems/carrierwave-49fdad1ec6ca/lib/carrierwave/uploader/versions.rb:270:in `block in cache_versions!'
/Users/robaldred/.rvm/gems/ruby-2.2.2/bundler/gems/carrierwave-49fdad1ec6ca/lib/carrierwave/uploader/versions.rb:268:in `each'
/Users/robaldred/.rvm/gems/ruby-2.2.2/bundler/gems/carrierwave-49fdad1ec6ca/lib/carrierwave/uploader/versions.rb:268:in `cache_versions!'
/Users/robaldred/.rvm/gems/ruby-2.2.2/bundler/gems/carrierwave-49fdad1ec6ca/lib/carrierwave/uploader/callbacks.rb:18:in `block in with_callbacks'
/Users/robaldred/.rvm/gems/ruby-2.2.2/bundler/gems/carrierwave-49fdad1ec6ca/lib/carrierwave/uploader/callbacks.rb:18:in `each'
/Users/robaldred/.rvm/gems/ruby-2.2.2/bundler/gems/carrierwave-49fdad1ec6ca/lib/carrierwave/uploader/callbacks.rb:18:in `with_callbacks'
/Users/robaldred/.rvm/gems/ruby-2.2.2/bundler/gems/carrierwave-49fdad1ec6ca/lib/carrierwave/uploader/cache.rb:127:in `cache!'
/Users/robaldred/.rvm/gems/ruby-2.2.2/bundler/gems/carrierwave-49fdad1ec6ca/lib/carrierwave/mounter.rb:43:in `block in cache'
/Users/robaldred/.rvm/gems/ruby-2.2.2/bundler/gems/carrierwave-49fdad1ec6ca/lib/carrierwave/mounter.rb:41:in `map'
/Users/robaldred/.rvm/gems/ruby-2.2.2/bundler/gems/carrierwave-49fdad1ec6ca/lib/carrierwave/mounter.rb:41:in `cache'
/Users/robaldred/.rvm/gems/ruby-2.2.2/bundler/gems/carrierwave-49fdad1ec6ca/lib/carrierwave/mount.rb:148:in `file='
/Users/robaldred/.rvm/gems/ruby-2.2.2/bundler/gems/carrierwave-49fdad1ec6ca/lib/carrierwave/orm/activerecord.rb:72:in `file='
```

I think this is the problem line `carrierwave/processing/rmagick.rb` is the problem, maybe it should probably use the extension as passed if it differs only by case?

Here's my version block which i basically took from the [wiki](https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Customize-your-version-file-names)

```
def filename 
    "original.#{model.file.file.extension}" if original_filename 
end

version :thumb, :if => :thumbable? do
  process :cover
  process :resize_to_fill => [160, 160]
  process :convert => :jpg
  process :set_content_type_jpg
  def full_filename (for_file = model.file.file)
     'thumb.jpg'
  end
end

def cover
  manipulate! do |frame, index|
    frame if index.zero? # take only the first page of the file
  end
end
```

If I remove the stuff for converting to jpg it works as expected, however I want to force convert to jpg.
It's common on the system I'm building because is a document (pdf) and photo storage, a lot of cameras seem to output their images with uppercase extensions, and I need to ensure the PDF cover is jpg not pdf.

I'm wondering if this is because my file system is case-insensitive, which i think is standard OSX.

**Comment by mshibuya** [comment]
Yes this is due to OS X filesystem's case-insensitivity, there's nothing we can do.
