### ISSUE TITLE
Uninitialized Constant Carrierwave::Storage::Fog

### ISSUE THREAD

**Issue by charliepugh92** [carrierwaveuploader/carrierwave#2023]
I just can't seem to get this to work. I have this in my gemfile as per the documentation:

```
gem 'carrierwave', '>= 1.0.0.beta', '< 2.0'
gem 'fog-aws'
```

Here's my initializers/carrierwave.rb file:

```
if Rails.env.test? or Rails.env.development?
  CarrierWave.configure do |config|
    config.storage = :file
    config.root = "#{Rails.root}/tmp"
    config.cache_dir = "#{Rails.root}/tmp/images"
  end
else
  CarrierWave.configure do |config|
    config.storage = :fog
		config.fog_provider = 'fog/aws'  
    config.fog_credentials = {
      :provider => 'AWS',
      :aws_access_key_id => ENV['AWS_ACCESS_KEY_ID'],
      :aws_secret_access_key => ENV['AWS_SECRET_ACCESS_KEY'],
      :region => ENV['AWS_S3_REGION']
    }
    config.fog_directory = ENV['AWS_S3_BUCKET_NAME']
    config.asset_host = "#{ENV['AWS_S3_ASSET_URL']}/#{ENV['AWS_S3_BUCKET_NAME']}"
  end
end
```

I feel like I have to be missing something, but at this point it feels like it's broken. I'm hosting this on Heroku, and I can't get the Revision App for my pull request with this in it to build.

**Comment by mshibuya** [comment]
Full stack trace please.

**Comment by charliepugh92** [comment]
```
Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       rake aborted!
       NameError: uninitialized constant CarrierWave::Storage::Fog
       /tmp/build_1b692a98e2d6c7c67fb38f83d14c5f37/ccm-innovation-prayerstream-api-54229bf56d9390f83bbcea0d56cef6061b8a915b/vendor/bundle/ruby/2.2.0/gems/carrierwave-1.0.0.beta/lib/carrierwave/uploader/configuration.rb:77:in `eval'
       /tmp/build_1b692a98e2d6c7c67fb38f83d14c5f37/ccm-innovation-prayerstream-api-54229bf56d9390f83bbcea0d56cef6061b8a915b/vendor/bundle/ruby/2.2.0/gems/carrierwave-1.0.0.beta/lib/carrierwave/uploader/configuration.rb:77:in `eval'
       /tmp/build_1b692a98e2d6c7c67fb38f83d14c5f37/ccm-innovation-prayerstream-api-54229bf56d9390f83bbcea0d56cef6061b8a915b/vendor/bundle/ruby/2.2.0/gems/carrierwave-1.0.0.beta/lib/carrierwave/uploader/configuration.rb:77:in `storage'
       /tmp/build_1b692a98e2d6c7c67fb38f83d14c5f37/ccm-innovation-prayerstream-api-54229bf56d9390f83bbcea0d56cef6061b8a915b/config/initializers/carrierwave.rb:9:in `block in <top (required)>'
       /tmp/build_1b692a98e2d6c7c67fb38f83d14c5f37/ccm-innovation-prayerstream-api-54229bf56d9390f83bbcea0d56cef6061b8a915b/vendor/bundle/ruby/2.2.0/gems/carrierwave-1.0.0.beta/lib/carrierwave/uploader/configuration.rb:158:in `configure'
       /tmp/build_1b692a98e2d6c7c67fb38f83d14c5f37/ccm-innovation-prayerstream-api-54229bf56d9390f83bbcea0d56cef6061b8a915b/vendor/bundle/ruby/2.2.0/gems/carrierwave-1.0.0.beta/lib/carrierwave.rb:14:in `configure'
       /tmp/build_1b692a98e2d6c7c67fb38f83d14c5f37/ccm-innovation-prayerstream-api-54229bf56d9390f83bbcea0d56cef6061b8a915b/config/initializers/carrierwave.rb:8:in `<top (required)>'
       /tmp/build_1b692a98e2d6c7c67fb38f83d14c5f37/ccm-innovation-prayerstream-api-54229bf56d9390f83bbcea0d56cef6061b8a915b/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:652:in `block in load_config_initializer'
       /tmp/build_1b692a98e2d6c7c67fb38f83d14c5f37/ccm-innovation-prayerstream-api-54229bf56d9390f83bbcea0d56cef6061b8a915b/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:166:in `instrument'
       /tmp/build_1b692a98e2d6c7c67fb38f83d14c5f37/ccm-innovation-prayerstream-api-54229bf56d9390f83bbcea0d56cef6061b8a915b/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:651:in `load_config_initializer'
       /tmp/build_1b692a98e2d6c7c67fb38f83d14c5f37/ccm-innovation-prayerstream-api-54229bf56d9390f83bbcea0d56cef6061b8a915b/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
       /tmp/build_1b692a98e2d6c7c67fb38f83d14c5f37/ccm-innovation-prayerstream-api-54229bf56d9390f83bbcea0d56cef6061b8a915b/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:615:in `each'
       /tmp/build_1b692a98e2d6c7c67fb38f83d14c5f37/ccm-innovation-prayerstream-api-54229bf56d9390f83bbcea0d56cef6061b8a915b/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:615:in `block in <class:Engine>'
       /tmp/build_1b692a98e2d6c7c67fb38f83d14c5f37/ccm-innovation-prayerstream-api-54229bf56d9390f83bbcea0d56cef6061b8a915b/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
       /tmp/build_1b692a98e2d6c7c67fb38f83d14c5f37/ccm-innovation-prayerstream-api-54229bf56d9390f83bbcea0d56cef6061b8a915b/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
       /tmp/build_1b692a98e2d6c7c67fb38f83d14c5f37/ccm-innovation-prayerstream-api-54229bf56d9390f83bbcea0d56cef6061b8a915b/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
       /tmp/build_1b692a98e2d6c7c67fb38f83d14c5f37/ccm-innovation-prayerstream-api-54229bf56d9390f83bbcea0d56cef6061b8a915b/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
       /tmp/build_1b692a98e2d6c7c67fb38f83d14c5f37/ccm-innovation-prayerstream-api-54229bf56d9390f83bbcea0d56cef6061b8a915b/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
       /tmp/build_1b692a98e2d6c7c67fb38f83d14c5f37/ccm-innovation-prayerstream-api-54229bf56d9390f83bbcea0d56cef6061b8a915b/config/environment.rb:5:in `<top (required)>'
       /tmp/build_1b692a98e2d6c7c67fb38f83d14c5f37/ccm-innovation-prayerstream-api-54229bf56d9390f83bbcea0d56cef6061b8a915b/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:328:in `require_environment!'
       /tmp/build_1b692a98e2d6c7c67fb38f83d14c5f37/ccm-innovation-prayerstream-api-54229bf56d9390f83bbcea0d56cef6061b8a915b/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:443:in `block in run_tasks_blocks'
       /tmp/build_1b692a98e2d6c7c67fb38f83d14c5f37/ccm-innovation-prayerstream-api-54229bf56d9390f83bbcea0d56cef6061b8a915b/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
       /tmp/build_1b692a98e2d6c7c67fb38f83d14c5f37/ccm-innovation-prayerstream-api-54229bf56d9390f83bbcea0d56cef6061b8a915b/vendor/bundle/ruby/2.2.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
```

**Comment by mshibuya** [comment]
Moving `config.storage = :fog` after `config.fog_credentials = ...` line will solve it.

**Comment by tonytonyjan** [comment]
I put `require 'carrierwave/storage/fog'` in `config/initializers/carrierwave.rb` to solve the problem.

**Comment by synth** [comment]
In my case, I was trying to stand up a new staging server and the issue was that somehow the fog gem (and a couple others) had gotten deleted. Yet running bundle install did not fix the issue.

Check the status of the gem with: 

    bundle show fog

You have a problem if it shows as something like: 

    The gem fog has been deleted. It was installed at:
    /home/user/sites/mysite.com/shared/bundle/ruby/2.2.0/gems/fog-1.38

You can fix by uninstalling:

    bundle exec gem uninstall fog

And then bundle install manually and check again.

    bundle install --path /home/web/sites/mysite.com/shared/bundle --without development test --deployment

**Comment by fowkswe** [comment]
If someone else happens upon this and the suggested fixes aren't working, check the location of your initializer - I had mine in `config`, not `config/intitalizers`....
