### ISSUE TITLE
Frozen NilClass error when overwriting filename method

### ISSUE THREAD

**Issue by RNBrandt** [carrierwaveuploader/carrierwave#2032]
When using the [Random Filename](https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Create-random-and-unique-filenames-for-all-versioned-files#random-filenames), we received the following error. 

Methods defined:

```
class PhotoUploader < CarrierWave::Uploader::Base
  def filename
     "#{secure_token(10)}.#{file.extension}" if original_filename.present?
  end

  protected
  def secure_token(length=16)
    var = :"@#{mounted_as}_secure_token"
    model.instance_variable_get(var) or model.instance_variable_set(var, SecureRandom.hex(length/2))
  end
end
```

Error received:

```
RuntimeError (can't modify frozen NilClass):
  app/uploaders/photo_uploader.rb:34:in `instance_variable_set'
  app/uploaders/photo_uploader.rb:34:in `secure_token'
  app/uploaders/photo_uploader.rb:25:in `filename'
  app/services/photo_preparer.rb:35:in `store_uploaded_file'
  app/services/photo_preparer.rb:23:in `store_file'
  app/services/photo_preparer.rb:12:in `store'
  app/services/photo_preparer.rb:3:in `store'
  app/controllers/api/v1/photos_controller.rb:11:in `create'
```

If the docs are out of date, we are happy to update them.  We just wanted to check that it was a documentation error rather than a user error first.

**Comment by mshibuya** [comment]
`model` appears to be `nil`, make sure to use your uploader in mounted manner, not just `PhotoUploader.new`.
