### ISSUE TITLE
How to retrieve the MiniMagick error that was rescued?

### ISSUE THREAD

**Issue by Seybo** [carrierwaveuploader/carrierwave#2098]
I'm having this error with CarrierWave

```
CarrierWave::ProcessingError (translation missing: en.errors.messages.mini_magick_processing_error):
  carrierwave (1.0.0.rc) lib/carrierwave/processing/mini_magick.rb:308:in `rescue in manipulate!'
  carrierwave (1.0.0.rc) lib/carrierwave/processing/mini_magick.rb:288:in `manipulate!'
  carrierwave (1.0.0.rc) lib/carrierwave/processing/mini_magick.rb:155:in `resize_to_fit'
  carrierwave (1.0.0.rc) lib/carrierwave/uploader/processing.rb:82:in `block in process!'
  carrierwave (1.0.0.rc) lib/carrierwave/uploader/processing.rb:74:in `each'
  carrierwave (1.0.0.rc) lib/carrierwave/uploader/processing.rb:74:in `process!'
  carrierwave (1.0.0.rc) lib/carrierwave/uploader/callbacks.rb:14:in `block in with_callbacks'
```

but I need to now the rescued error from MiniMagic. How can I get it?

**Comment by gregersen12** [comment]
I had a similar issue. 
Were you trying to add multiple files as well?

Either way; the callstack doesn't give much, it would be convenient if there was indeed a way to grab the rescued error!
