### ISSUE TITLE
Incompatibity between 0.11.2 and 1.0.0

### ISSUE THREAD

**Issue by okkez** [carrierwaveuploader/carrierwave#2124]
I use this gem with Rails following configuration:

```ruby
CarrierWave.configure do |config|
  if ENV["S3_ACCESS_KEY_ID"]
    config.storage :fog

    config.fog_credentials = {
      provider:              "AWS",
      aws_access_key_id:     ENV["S3_ACCESS_KEY_ID"],
      aws_secret_access_key: ENV["S3_SECRET_ACCESS_KEY"],
      region:                ENV["S3_REGION"]
    }
    config.asset_host    = ENV["ASSET_HOST"]
    config.fog_directory = ENV["S3_BUCKET"]
    config.fog_attributes = {"Cache-Control" => "max-age=#{365.days.to_i}"}
  else
    config.storage :file
  end
end
```

This works well with 0.11.2 but this does not work at all with 1.0.0.

Errors with 1.0.0:

```
 NameError: uninitialized constant CarrierWave::Storage::Fog
vendor/bundle/ruby/2.3.0/gems/carrierwave-1.0.0/lib/carrierwave/uploader/configuration.rb:77:in `eval'
vendor/bundle/ruby/2.3.0/gems/carrierwave-1.0.0/lib/carrierwave/uploader/configuration.rb:77:in `eval'
```

This is caused by [here](https://github.com/carrierwaveuploader/carrierwave/blob/v1.0.0/lib/carrierwave/uploader/configuration.rb#L77).

I noticed that move `config.storage :fog` after `config.fog_xxx` to invoke `eager_load_fog` before eval `"CarrierWave::Storage::Fog"`.

For example:

```ruby
CarrierWave.configure do |config|
  if ENV["S3_ACCESS_KEY_ID"]
    config.fog_credentials = {
      provider:              "AWS",
      aws_access_key_id:     ENV["S3_ACCESS_KEY_ID"],
      aws_secret_access_key: ENV["S3_SECRET_ACCESS_KEY"],
      region:                ENV["S3_REGION"]
    }
    config.asset_host    = ENV["ASSET_HOST"]
    config.fog_directory = ENV["S3_BUCKET"]
    config.fog_attributes = {"Cache-Control" => "max-age=#{365.days.to_i}"}

    config.storage :fog
  else
    config.storage :file
  end
end
```

Is this intentional?

**Comment by afirth** [comment]
Broken for us in Prod

**Comment by CodingAnarchy** [comment]
I had to do the same workaround to get this to load.  Would appreciate some fix for that - configuration variables should be order-independent, IMO.

**Comment by mshibuya** [comment]
Dup of #2023, solution is [here](https://github.com/carrierwaveuploader/carrierwave/issues/2023#issuecomment-252407542).
