### ISSUE TITLE
undefined method `new` for Array

### ISSUE THREAD

**Issue by lucianosousa** [carrierwaveuploader/carrierwave#2170]
I'm trying upgrade the carrierwave version of: https://github.com/call4paperz/call4paperz

from 0.10.0 to the stable one and I'm receiving this error on production:

```
irb(main):001:0> u = User.new
irb(main):003:0> u.email = 'example@email.com'
irb(main):004:0> u.password = 'xxxx'
irb(main):005:0> u.password_confirmation = 'xxxx'
irb(main):006:0> u.save

NoMethodError: undefined method `new' for #<Array:0x007f08cc348290>
	from /app/vendor/bundle/ruby/2.4.0/gems/carrierwave-1.1.0/lib/carrierwave/uploader/store.rb:88:in `storage'
	from /app/vendor/bundle/ruby/2.4.0/gems/carrierwave-1.1.0/lib/carrierwave/uploader/proxy.rb:33:in `identifier'
	from /app/vendor/bundle/ruby/2.4.0/gems/carrierwave-1.1.0/lib/carrierwave/mounter.rb:25:in `map'
	from /app/vendor/bundle/ruby/2.4.0/gems/carrierwave-1.1.0/lib/carrierwave/mounter.rb:25:in `identifiers'
	from /app/vendor/bundle/ruby/2.4.0/gems/carrierwave-1.1.0/lib/carrierwave/mount.rb:179:in `write_photo_identifier'
	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:432:in `block in make_lambda'
	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:164:in `block in halting'
	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `block in call'
	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `each'
	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `call'
	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
	from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/callbacks.rb:302:in `create_or_update'
	from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/persistence.rb:120:in `save'
	from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/validations.rb:37:in `save'
	from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/attribute_methods/dirty.rb:21:in `save'

```

it's a heroku env with all AWS keys configured.
any thoughts?

**Comment by lucianosousa** [comment]
So, I found the problem:

the doc says to configure my storage like:

```
config.storage = :fog
```

the error was fixed when I did:

```
config.storage :fog
```

Is that a real problem?
