### ISSUE TITLE
Uncaught exception: uninitialized constant CarrierWave::Storage::Fog

### ISSUE THREAD

**Issue by JohnMerlino2** [carrierwaveuploader/carrierwave#2269]
I have two models which require photo uploads. User has an avatar attribute and Loop has a photo attribute. I have the following in User:

`    mount_uploader :avatar, AvatarUploader
`
And it works with no errors. Then I added the following in Loop:

`    mount_uploader :photo, AvatarUploader
`
And it would raise the error. I even tried creating a new uploader class:

`    mount_uploader :photo, PhotoUploader
`
And the uploader class:

```
class PhotoUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick

  storage :fog

  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  def default_url(*args)
    "/uploads/fallback/" + [version_name, "default.png"].compact.join('_')
  end

  version :web do
    version :thumb do
      process resize_to_fit: [32, 32]
    end
    version :preview do
      process resize_to_fit: [128, 128]
    end
    version :full do
      process resize_to_fit: [640, 500]
    end
  end

  version :mobile do
    version :thumb do
      process resize_to_fit: [32, 32]
    end
    version :preview do
      process resize_to_fit: [128, 128]
    end
    version :full do
      process resize_to_fit: [640, 500]
    end
  end

  def extension_whitelist
    %w(jpg jpeg gif png)
  end

  def content_type_whitelist
    /image\//
  end

  def content_type_blacklist
    ['application/text', 'application/json']
  end
end
```
It gives me following error:

```
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/carrierwave-1.2.2/lib/carrierwave/uploader/configuration.rb:78:in `eval'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/carrierwave-1.2.2/lib/carrierwave/uploader/configuration.rb:78:in `eval'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/carrierwave-1.2.2/lib/carrierwave/uploader/configuration.rb:78:in `storage'
	/Users/itsme/projects/my_app/app/uploaders/photo_uploader.rb:8:in `<class:PhotoUploader>'
	/Users/itsme/projects/my_app/app/uploaders/photo_uploader.rb:1:in `<top (required)>'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/activesupport-5.0.0.1/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/activesupport-5.0.0.1/lib/active_support/concurrency/share_lock.rb:117:in `exclusive'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/activesupport-5.0.0.1/lib/active_support/dependencies/interlock.rb:11:in `loading'
	/Users/itsme/projects/my_app/app/models/loop.rb:10:in `<class:Loop>'
	/Users/itsme/projects/my_app/app/models/loop.rb:1:in `<top (required)>'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/activesupport-5.0.0.1/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/activesupport-5.0.0.1/lib/active_support/concurrency/share_lock.rb:117:in `exclusive'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/activesupport-5.0.0.1/lib/active_support/dependencies/interlock.rb:11:in `loading'
	/Users/itsme/projects/my_app/config/initializers/application_controller_renderer.rb:7:in `<top (required)>'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/railties-5.0.0.1/lib/rails/engine.rb:648:in `block in load_config_initializer'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:166:in `instrument'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/railties-5.0.0.1/lib/rails/engine.rb:647:in `load_config_initializer'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/railties-5.0.0.1/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/railties-5.0.0.1/lib/rails/engine.rb:611:in `each'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/railties-5.0.0.1/lib/rails/engine.rb:611:in `block in <class:Engine>'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `instance_exec'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `run'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/railties-5.0.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	/Users/itsme/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	/Users/itsme/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	/Users/itsme/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	/Users/itsme/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	/Users/itsme/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/railties-5.0.0.1/lib/rails/initializable.rb:44:in `each'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/railties-5.0.0.1/lib/rails/initializable.rb:44:in `tsort_each_child'
	/Users/itsme/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:415:in `call'
	/Users/itsme/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
	/Users/itsme/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	/Users/itsme/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
	/Users/itsme/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
	/Users/itsme/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	/Users/itsme/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	/Users/itsme/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/railties-5.0.0.1/lib/rails/initializable.rb:54:in `run_initializers'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/railties-5.0.0.1/lib/rails/application.rb:352:in `initialize!'
	/Users/itsme/projects/my_app/config/environment.rb:5:in `<top (required)>'
	/Users/itsme/projects/my_app/config.ru:3:in `require_relative'
	/Users/itsme/projects/my_app/config.ru:3:in `block in <main>'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
	/Users/itsme/projects/my_app/config.ru:in `new'
	/Users/itsme/projects/my_app/config.ru:in `<main>'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/rack-2.0.1/lib/rack/server.rb:318:in `build_app_and_options_from_config'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/rack-2.0.1/lib/rack/server.rb:218:in `app'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/railties-5.0.0.1/lib/rails/commands/server.rb:59:in `app'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/rack-2.0.1/lib/rack/server.rb:353:in `wrapped_app'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/railties-5.0.0.1/lib/rails/commands/server.rb:124:in `log_to_stdout'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/railties-5.0.0.1/lib/rails/commands/server.rb:77:in `start'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `tap'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `server'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	/Users/itsme/.rvm/gems/ruby-2.3.0@my_app/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	/Users/itsme/projects/my_app/bin/rails:9:in `require'
	/Users/itsme/projects/my_app/bin/rails:9:in `<top (required)>
```
config/initializers/carrierwave.rb has the following:

```
CarrierWave.configure do |config|
  config.fog_provider = 'fog/aws'
  config.fog_credentials = {
    provider:              'AWS',
    aws_access_key_id:     ENV.fetch('AWS_ACCESS_KEY_ID'),
    aws_secret_access_key: ENV.fetch('AWS_SECRET_ACCESS_KEY'),
    region:                ENV.fetch('AWS_REGION'),
    host:                  "s3.#{ENV.fetch('AWS_REGION')}.amazonaws.com",
    endpoint:              nil
  }
  config.fog_directory  = 'mystuff'
end

```
I am not sure why I am getting this error. Any ideas?

**Comment by mrsweaters** [comment]
Is this in your gemfile? https://github.com/fog/fog-aws

**Comment by Rubioli** [comment]
I had the same problem when I changed `storage` and the fix was to restart the server. As you can know `uninitialized constant` comes when something needs to be initialized on start.

**Comment by mshibuya** [comment]
Please see if above advice works.
