### ISSUE TITLE
private method `select' called for nil:NilClass on uploader/versions

### ISSUE THREAD

**Issue by fredbaa** [carrierwaveuploader/carrierwave#2369]
I'm trying to upgrade our gem from 0.10.0 to the latest version 1.3.1, and when I tried to store the image, it raises this `private method 'select' called for nil:NilClass` issue. There were no issues before when we use the 0.10.0 version so I'm not sure if we need to initialize something on the uploaders on upgrade. We are running Rails 4, ruby 2.1.9

syntax:
```
image = ::V2::Image.new(source: params[:v2_banner][:image_source])

## params[:v2_banner][:image_source] is ActionDispatch::Http::UploadedFile  
## which is coming from the file_field
```

error trace:
```
  carrierwave (1.3.1) lib/carrierwave/uploader/versions.rb:247:in `active_versions'
  carrierwave (1.3.1) lib/carrierwave/uploader/versions.rb:241:in `assign_parent_cache_id'
  carrierwave (1.3.1) lib/carrierwave/uploader/callbacks.rb:16:in `block in with_callbacks'
  carrierwave (1.3.1) lib/carrierwave/uploader/callbacks.rb:16:in `with_callbacks'
  carrierwave (1.3.1) lib/carrierwave/uploader/cache.rb:137:in `cache!'
  carrierwave (1.3.1) lib/carrierwave/mounter.rb:44:in `block in cache'
  carrierwave (1.3.1) lib/carrierwave/mounter.rb:42:in `cache'
  carrierwave (1.3.1) lib/carrierwave/mount.rb:146:in `source='
  carrierwave (1.3.1) lib/carrierwave/orm/activerecord.rb:70:in `source='
  activerecord (4.0.0) lib/active_record/attribute_assignment.rb:42:in `_assign_attribute'
  activerecord (4.0.0) lib/active_record/attribute_assignment.rb:29:in `block in assign_attributes'
  activerecord (4.0.0) lib/active_record/attribute_assignment.rb:23:in `assign_attributes'
  activerecord (4.0.0) lib/active_record/core.rb:192:in `initialize'
  activerecord (4.0.0) lib/active_record/inheritance.rb:27:in `new'
  app/controllers/admin2/v2_banners_controller.rb:31:in `create'
```

We are using MiniMagick also for versioning, and we didnt encounter any issues on the old version.

**Comment by mshibuya** [comment]
Do you override `versions` ? Could you show me your uploader?

**Comment by mshibuya** [comment]
Please reopen on update.
