### ISSUE TITLE
Error When Using fog-aws and fog_provider Not Set: cannot load such file -- fog (LoadError) 

### ISSUE THREAD

**Issue by sshaw** [carrierwaveuploader/carrierwave#2434]
Docs need to be updated when using S3 with fog-aws. In their current form one gets the following error when starting the application:

```
...
	 6: from /Users/sshaw/code/ruby/xxx/config/initializers/carrierwave.rb:16:in `block in <top (required)>'
	 5: from /Users/sshaw/.rvm/gems/ruby-2.5.1/gems/carrierwave-1.2.3/lib/carrierwave/uploader/configuration.rb:139:in `fog_credentials='
	 4: from /Users/sshaw/.rvm/gems/ruby-2.5.1/gems/carrierwave-1.2.3/lib/carrierwave/uploader/configuration.rb:124:in `eager_load_fog'
	 3: from /Users/sshaw/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
	 2: from /Users/sshaw/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	 1: from /Users/sshaw/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/Users/sshaw/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require': cannot load such file -- fog (LoadError)
```

One must set `config.fog_provider = 'fog/aws'` for it to work.

**Comment by ogelacinyc** [comment]
Your carrierwave's version is  1.2.3. It need to set `config.fog_provider = 'fog/aws'`
if you read a readme with master branch, you set up a configure for version 2.0
`config.fog_provider = 'fog/aws'` is deprecated option from 2.0
