### ISSUE TITLE
"No such file or directory" when upgrading to 2.0.2

### ISSUE THREAD

**Issue by mockdeep** [carrierwaveuploader/carrierwave#2435]
This might be related to https://github.com/carrierwaveuploader/carrierwave/issues/2413, but appears to be slightly different. In that case it looks like it's trying to grab the cached image, whereas in our case it seems to be trying to grab the original image. Oddly, this error is only happening on our CI servers, and everything works fine for my on my local machine. Here's the stack trace:

```
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/rof/src/github.com/InformedK12/synchroform/tmp/uploads/doc/pdf/1/examplereleaseform.pdf
/home/rof/cache/bundler/ruby/2.5.0/gems/carrierwave-2.0.2/lib/carrierwave/sanitized_file.rb:160:in `initialize'
/home/rof/cache/bundler/ruby/2.5.0/gems/carrierwave-2.0.2/lib/carrierwave/sanitized_file.rb:160:in `open'
/home/rof/cache/bundler/ruby/2.5.0/gems/carrierwave-2.0.2/lib/carrierwave/sanitized_file.rb:160:in `read'
/home/rof/src/github.com/InformedK12/synchroform/app/workers/doc_conversion_worker.rb:43:in `block in create_temp_file'
/home/rof/src/github.com/InformedK12/synchroform/app/workers/doc_conversion_worker.rb:42:in `tap'
/home/rof/src/github.com/InformedK12/synchroform/app/workers/doc_conversion_worker.rb:42:in `create_temp_file'
/home/rof/src/github.com/InformedK12/synchroform/app/workers/doc_conversion_worker.rb:58:in `file'
/home/rof/src/github.com/InformedK12/synchroform/app/workers/doc_conversion_worker.rb:62:in `current_path'
/home/rof/cache/bundler/ruby/2.5.0/gems/carrierwave-2.0.2/lib/carrierwave/processing/rmagick.rb:352:in `manipulate!'
/home/rof/src/github.com/InformedK12/synchroform/app/workers/doc_conversion_worker.rb:28:in `create_pages!'
/home/rof/src/github.com/InformedK12/synchroform/app/workers/doc_conversion_worker.rb:17:in `perform'
```

You may notice that our source is inside of a worker instead of an uploader. Our use case is a little weird in that we've shoehorned the RMagick logic into a worker in order to background it. Here's the worker, where we've provided the methods that CarrierWave expects:

```rb
# frozen_string_literal: true

class DocConversionWorker

  include CarrierWave::RMagick, Sidekiq::Worker
  sidekiq_options queue: :critical

  def perform(doc_id)
    @doc = Doc.unscoped.find(doc_id)
    @doc.with_lock do
      return if @doc.pages_processing?

      @doc.update!(pages_processing: true)
    end

    begin
      create_pages!
    ensure
      @doc.update!(pages_processing: false)
    end

    @doc.update!(pdf_processing: false)
  end

private

  def create_pages!
    manipulate! format: 'png', read: { density: 216 } do |img, index|
      temp = Tempfile.new(['image', '.png'])
      this_img = img.write('png:' + temp.path)

      page = @doc.pages.where(seq: index + 1).first_or_initialize
      page.update!(width: img.columns, height: img.rows, img: temp)

      this_img
    end
  end

  def create_temp_file
    # we save to a local temp because `manipulate!` has the side
    # effect of re-writing the original file, which we don't want to change
    Tempfile.new('temp').tap do |file|
      file.write(@doc.pdf.file.read.force_encoding('utf-8'))
      file.rewind
    end
  end

  # methods required by CarrierWave::RMagick
  def permissions
    CarrierWave::Uploader::Base.permissions
  end

  def directory_permissions
    CarrierWave::Uploader::Base.directory_permissions
  end

  def file
    @file ||= CarrierWave::SanitizedFile.new(create_temp_file)
  end

  def current_path
    @current_path ||= file.path
  end

  def cached?
    @doc.pdf.cached?
  end

  def cache_stored_file!
    @doc.pdf.cache_stored_file!
  end

end
```

**Comment by mockdeep** [comment]
Upon further investigation, it appears that the issue is happening earlier, prior to all of the logic in the worker class. When I check for the file on my local machine it is fine, but for some reason it does not exist on CI:

```irb
# local development env
File.exist?(@doc.pdf.path) # => true
# CI machine
File.exist?(@doc.pdf.path) # => false
```

It's the same results whether I run in dev or test mode. The CarrierWave settings are the same for each.

**Comment by mshibuya** [comment]
It may be just your CI server has no ghostscript installed.
cf. https://github.com/carrierwaveuploader/carrierwave/commit/bd2d649b1c5a9215919c82d8aad9854e5acae831
