### ISSUE TITLE
reprocessing versions produces "uninitialized constant MimeMagic::Encoding" on 0.11.1

### ISSUE THREAD

**Issue by KONSTRUKTEUR** [carrierwaveuploader/carrierwave#2441]
I get `uninitialized constant MimeMagic::Encoding` when trying to recreate versions:

```
>> Diapo.last.file_name.recreate_versions!
   Diapo Load (0.4ms)  SELECT 'diapos'.* FROM 'diapos' ORDER BY 'diapos'.'id' DESC LIMIT 1
NameError: uninitialized constant MimeMagic::Encoding
	from /Users/account/.rvm/gems/project/gems/mimemagic-0.3.3/lib/mimemagic.rb:116:in 'magic_match'
	from /Users/account/.rvm/gems/project/gems/mimemagic-0.3.3/lib/mimemagic.rb:81:in 'by_magic'
	from /Users/account/.rvm/gems/project/gems/carrierwave-0.11.1/lib/carrierwave/sanitized_file.rb:318:in 'mime_magic_content_type'
	from /Users/account/.rvm/gems/project/gems/carrierwave-0.11.1/lib/carrierwave/sanitized_file.rb:250:in 'content_type'
	from /Users/account/.rvm/gems/project/gems/carrierwave-0.11.1/lib/carrierwave/uploader/cache.rb:96:in 'sanitized_file'
	from /Users/account/.rvm/gems/project/gems/carrierwave-0.11.1/lib/carrierwave/uploader/cache.rb:128:in 'cache!'
	from /Users/account/.rvm/gems/project/gems/carrierwave-0.11.1/lib/carrierwave/uploader/versions.rb:226:in 'recreate_versions!'
	from (irb):3
>> exit
```

Upload works, but when trying to reprocess the upload after a parameter change of the version I get this error.

**Comment by mshibuya** [comment]
`Encoding` should be available as a Ruby built-in library. What Ruby implementation do you use?

**Comment by KONSTRUKTEUR** [comment]
I do not remember, what I used in 2019 for a ruby. I encountered this issue some time ago.

**Comment by mshibuya** [comment]
OK, then closing.
