### ISSUE TITLE
"No implicit conversion" error with v2.2.1

### ISSUE THREAD

**Issue by robpark** [carrierwaveuploader/carrierwave#2559]
Using carrierwave-aws 1.5.0, Rails 5.2.5, Ruby 2.6.6.
If I bump carrierwave to 2.2.1, I'm getting errors saving CSV files: `no implicit conversion of CSV into String`. 
Carrierwave 2.2.0 is working fine.

I'm not sure what other information you might find useful, but wanted to bring the issue to your attention.

**Comment by pjmartorell** [comment]
@robpark could you paste the backtrace of the error?

**Comment by pjmartorell** [comment]
@robpark I found a bug and it's addressed in #2562

**Comment by robpark** [comment]
I don't have a backtrace convenient, but will have time tomorrow to reproduce.
I'll also track #2562 and will be happy to test when a patch is out.
Thanks.

**Comment by robpark** [comment]
Here's a backtrace:

```
TypeError:
  no implicit conversion of CSV into String
# /home/rof/cache/bundler/ruby/2.6.0/gems/marcel-1.0.1/lib/marcel/magic.rb:80:in `extname'
# /home/rof/cache/bundler/ruby/2.6.0/gems/marcel-1.0.1/lib/marcel/magic.rb:80:in `by_path'
# /home/rof/cache/bundler/ruby/2.6.0/gems/carrierwave-2.2.1/lib/carrierwave/sanitized_file.rb:338:in `marcel_magic_content_type'
# /home/rof/cache/bundler/ruby/2.6.0/gems/carrierwave-2.2.1/lib/carrierwave/sanitized_file.rb:264:in `content_type'
# /home/rof/cache/bundler/ruby/2.6.0/gems/carrierwave-2.2.1/lib/carrierwave/sanitized_file.rb:221:in `copy_to'
# /home/rof/cache/bundler/ruby/2.6.0/gems/carrierwave-2.2.1/lib/carrierwave/uploader/cache.rb:141:in `cache!'
# /home/rof/cache/bundler/ruby/2.6.0/gems/carrierwave-2.2.1/lib/carrierwave/mounter.rb:63:in `block (2 levels) in cache'
# /home/rof/cache/bundler/ruby/2.6.0/gems/carrierwave-2.2.1/lib/carrierwave/mounter.rb:176:in `handle_error'
# /home/rof/cache/bundler/ruby/2.6.0/gems/carrierwave-2.2.1/lib/carrierwave/mounter.rb:47:in `block in cache'
# /home/rof/cache/bundler/ruby/2.6.0/gems/carrierwave-2.2.1/lib/carrierwave/mounter.rb:46:in `map'
# /home/rof/cache/bundler/ruby/2.6.0/gems/carrierwave-2.2.1/lib/carrierwave/mounter.rb:46:in `cache'
# /home/rof/cache/bundler/ruby/2.6.0/gems/carrierwave-2.2.1/lib/carrierwave/mount.rb:146:in `file='
# /home/rof/cache/bundler/ruby/2.6.0/gems/carrierwave-2.2.1/lib/carrierwave/mount.rb:373:in `file='
# /home/rof/cache/bundler/ruby/2.6.0/gems/carrierwave-2.2.1/lib/carrierwave/orm/activerecord.rb:75:in `file='
# ./app/services/document_generator.rb:15:in `build'
# ./app/jobs/generate_update_files_job.rb:37:in `block (2 levels) in perform'
# ./app/jobs/generate_update_files_job.rb:31:in `each'
# ./app/jobs/generate_update_files_job.rb:31:in `block in perform'
# ./app/jobs/generate_update_files_job.rb:29:in `perform'
# /home/rof/cache/bundler/ruby/2.6.0/gems/i18n-1.8.10/lib/i18n.rb:309:in `with_locale'
# ./spec/jobs/generate_update_files_job_spec.rb:35:in `block (4 levels) in <top (required)>'
```

Let me know if I can provide any additional help.
Thanks!

**Comment by pjmartorell** [comment]
Thanks, as I suspected the bug is in `carrierwave-2.2.1/lib/carrierwave/sanitized_file.rb:338:in `marcel_magic_content_type'`. The PR I mentioned before fixes it, but we need to wait for @mshibuya to review it.
