### ISSUE TITLE
`cache_stored_file!` is not downloading the remote file as expected (Fog+Amazon S3)

### ISSUE THREAD

**Issue by danielricecodes** [carrierwaveuploader/carrierwave#2602]
I'm having an issue on Heroku when trying to use `cache_stored_file!` to download a remote file onto the local file system.  After calling `cache_stored_file!` on an uploader instance (see code below), when I try to access the file it is not found on the local file system anywhere.  I am not getting any file system level permission warnings/errors and yes, the file exists on S3 and I can download it just fine.

So why then am I getting `Errno::ENOENT` when I try to access the file?  Am I simply misunderstanding what this method does or is this an issue with CarrierWave 2.2.2 ? 

Thank you in advance.

```
irb(main): > s3_file.cache_stored_file!
=> [:assign_parent_cache_id, :cache_versions!]

irb(main): > File.open(s3_file.file.path)
Traceback (most recent call last):
       10: from bin/rails:4:in `<main>'
        9: from bin/rails:4:in `require'
        8: from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.7.2/lib/rails/commands.rb:18:in `<top (required)>'
        7: from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        6: from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:78:in `console'
        5: from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.7.2/lib/rails/commands/console_helper.rb:9:in `start'
        4: from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.7.2/lib/rails/commands/console.rb:65:in `start'
        3: from (irb):7
        2: from (irb):7:in `open'
        1: from (irb):7:in `initialize'
Errno::ENOENT (No such file or directory @ rb_sysopen - /app/tmp/uploads/1649437547-292587737743486-0001-8212/ReturnImages_20220329_1_1501958301.zip)
```

# Gemfile.lock
```
    carrierwave (2.2.2)
      activemodel (>= 5.0.0)
      activesupport (>= 5.0.0)
      addressable (~> 2.6)
      image_processing (~> 1.1)
      marcel (~> 1.0.0)
      mini_mime (>= 0.1.3)
      ssrf_filter (~> 1.0)
    fog-aws (3.12.0)
      fog-core (~> 2.1)
      fog-json (~> 1.1)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-core (2.2.4)
      builder
      excon (~> 0.71)
      formatador (~> 0.2)
      mime-types
```

# my uploader
```ruby
class ZipFileUploader < CarrierWave::Uploader::Base

  def store_dir
    "#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  def cache_dir
    File.join(Rails.root, 'tmp/uploads')
  end

  def extension_white_list
     %w(zip)
  end

end
```

**Comment by danielricecodes** [comment]
After reviewing several other issues and noticing that no one appears to be supporting this gem, I worked around the issue.  In case anyone else runs into this issue - I ended up using the [OpenURI](https://ruby-doc.org/stdlib-2.6.3/libdoc/open-uri/rdoc/OpenURI.html) module from standard lib.
