### ISSUE TITLE
fails on rails master

### ISSUE THREAD

**Issue by slbug** [carrierwaveuploader/carrierwave#533]
I understand that may be it's still to early to think about rails 3.2, but it may help in future. Right now 46 tests fails on master branch. First fail is on "CarrierWave::Mount.mount_uploader#image_url should get the url from a cached file's version"

Full trace

```
  1) CarrierWave::Mount.mount_uploader#image_url should get the url from a cached file's version
     Failure/Error: @instance.image = stub_file('test.jpg')
     NoMethodError:
       undefined method `parent_cache_id=' for {:uploader=>#<Class:0x0000000474c148>, :options=>{}}:Hash
     # ./lib/carrierwave/uploader/versions.rb:187:in `block in assign_parent_cache_id'
     # ./lib/carrierwave/uploader/versions.rb:186:in `each'
     # ./lib/carrierwave/uploader/versions.rb:186:in `assign_parent_cache_id'
     # ./lib/carrierwave/uploader/callbacks.rb:18:in `block in with_callbacks'
     # ./lib/carrierwave/uploader/callbacks.rb:18:in `each'
     # ./lib/carrierwave/uploader/callbacks.rb:18:in `with_callbacks'
     # ./lib/carrierwave/uploader/cache.rb:112:in `cache!'
     # ./lib/carrierwave/mount.rb:317:in `cache'
     # ./lib/carrierwave/mount.rb:173:in `image='
     # ./lib/carrierwave/mount.rb:158:in `image='
     # ./spec/mount_spec.rb:196:in `block (4 levels) in <top (required)>'

```

I'm trying to find why it happens, but still have no idea.

**Comment by fatuhoku** [comment]
So what's the solution to me getting
`NoMethodError: undefined method `remove_previously_stored_files_after_update' for nil:NilClass` in my rspec tests?

**Comment by lucienLopez** [comment]
If anyone else stumbles onto this:

In my case, it was due to a find_by_sql that did not retrieve picture field
